export const eleventhBatchQuestions = [
  {
    id: 1360,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q1. A cleanroom used for aseptic filling must maintain which pressure relationship relative to adjacent lower-grade areas?",
    options: ["Negative pressure", "Positive pressure", "Equal pressure", "No requirement"],
    correct: "Positive pressure",
    explanation: "Positive pressure helps air flow out of the cleanroom and reduces the chance that contaminated air enters from less clean areas.",
    explainCorrect: "Positive pressure is the correct answer.",
  },
  {
    id: 1361,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q2. How many milliliters of a 1:5000 w/v solution contain 2 mg of solute?",
    options: ["1 mL", "5 mL", "10 mL", "20 mL"],
    correct: "10 mL",
    explanation: "A 1:5000 solution contains 0.2 mg per mL, so 2 mg is contained in 10 mL.",
    explainCorrect: "10 mL is correct because 2 mg divided by 0.2 mg/mL equals 10 mL.",
  },
  {
    id: 1362,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q3. What is the maximum permitted number of viable colonies (CFU) in a Grade A (ISO 5) area during dynamic operation under EU GMP?",
    options: ["0 CFU", "1 CFU", "5 CFU", "10 CFU"],
    correct: "0 CFU",
    explanation: "Grade A is the critical aseptic zone, so no viable microbial growth is permitted during dynamic operation.",
    explainCorrect: "0 CFU is correct for Grade A dynamic monitoring.",
  },
  {
    id: 1363,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q4. A patient requires 600 mg of a drug. Tablets are available as 200 mg each. How many tablets should be given?",
    options: ["2 tablets", "3 tablets", "4 tablets", "5 tablets"],
    correct: "3 tablets",
    explanation: "600 mg divided by 200 mg per tablet gives 3 tablets.",
    explainCorrect: "3 tablets is the correct dose.",
  },
  {
    id: 1364,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q5. Which of the following is a critical quality attribute (CQA) for a tablet?",
    options: ["Batch number", "Dissolution rate", "Colour of the packaging box", "Name of the operator"],
    correct: "Dissolution rate",
    explanation: "Dissolution affects drug release and bioavailability, so it is a critical quality attribute.",
    explainCorrect: "Dissolution rate is the correct CQA.",
  },
  {
    id: 1365,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q6. A 250 mL infusion contains 25,000 units of heparin. The rate is 12 mL/hour. How many units per hour is the patient receiving?",
    options: ["600 units/h", "1200 units/h", "1800 units/h", "2400 units/h"],
    correct: "1200 units/h",
    explanation: "The solution contains 100 units per mL, so 12 mL/hour delivers 1200 units/hour.",
    explainCorrect: "1200 units/h is correct.",
  },
  {
    id: 1366,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q7. What does the term validation mean in GMP?",
    options: [
      "Checking finished products randomly",
      "Documented evidence that a process consistently produces a product meeting specifications",
      "Training all staff once per year",
      "Calibrating balances weekly",
    ],
    correct: "Documented evidence that a process consistently produces a product meeting specifications",
    explanation: "Validation is documented proof that a process, method, or system consistently performs as intended.",
    explainCorrect: "The documented evidence option is correct.",
  },
  {
    id: 1367,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q8. A child weighing 22 kg is prescribed 15 mg/kg/day of a drug in two divided doses. How many mg per dose?",
    options: ["165 mg", "220 mg", "330 mg", "82.5 mg"],
    correct: "165 mg",
    explanation: "22 kg times 15 mg/kg/day equals 330 mg/day, and two divided doses gives 165 mg per dose.",
    explainCorrect: "165 mg per dose is correct.",
  },
  {
    id: 1368,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q9. In a multi-product facility, cross-contamination is BEST prevented by:",
    options: [
      "Wearing colour-coded uniforms",
      "Using dedicated equipment and validated cleaning procedures",
      "Increasing air changes only",
      "Training operators every five years",
    ],
    correct: "Using dedicated equipment and validated cleaning procedures",
    explanation: "Dedicated equipment and validated cleaning are the most effective controls for cross-contamination risk.",
    explainCorrect: "Dedicated equipment plus validated cleaning is correct.",
  },
  {
    id: 1369,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q10. How many grams of dextrose are in 500 mL of a 5% w/v dextrose solution?",
    options: ["5 g", "10 g", "25 g", "50 g"],
    correct: "25 g",
    explanation: "A 5% w/v solution contains 5 g per 100 mL, so 500 mL contains 25 g.",
    explainCorrect: "25 g is correct.",
  },
  {
    id: 1370,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q11. What is the primary purpose of a Change Control system in pharmaceutical manufacturing?",
    options: [
      "To increase production speed",
      "To evaluate and approve changes that may affect product quality",
      "To track employee attendance",
      "To order new raw materials",
    ],
    correct: "To evaluate and approve changes that may affect product quality",
    explanation: "Change control ensures that changes are assessed for quality impact before they are implemented.",
    explainCorrect: "Evaluating and approving quality-impacting changes is correct.",
  },
  {
    id: 1371,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q12. A patient is prescribed 40 mg of furosemide IV. The ampoule contains 50 mg in 5 mL. What volume must be drawn up?",
    options: ["2 mL", "3 mL", "4 mL", "5 mL"],
    correct: "4 mL",
    explanation: "The concentration is 10 mg/mL, so 40 mg requires 4 mL.",
    explainCorrect: "4 mL is correct.",
  },
  {
    id: 1372,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q13. Which document provides the step-by-step instructions for manufacturing a specific batch?",
    options: [
      "Validation Master Plan",
      "Batch Manufacturing Record (BMR)",
      "Standard Operating Procedure (SOP) for cleaning",
      "Material Safety Data Sheet",
    ],
    correct: "Batch Manufacturing Record (BMR)",
    explanation: "The BMR contains the instructions, quantities, equipment, and in-process controls for a particular batch.",
    explainCorrect: "Batch Manufacturing Record (BMR) is correct.",
  },
  {
    id: 1373,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q14. Using alligation alternate, calculate the volume of 50% dextrose needed to prepare 1000 mL of 10% dextrose using 50% and 5% dextrose solutions.",
    options: ["111 mL", "222 mL", "333 mL", "500 mL"],
    correct: "111 mL",
    explanation: "The alligation ratio is 5 parts of 50% solution to 40 parts of 5% solution, making 1 part out of 9 total parts.",
    explainCorrect: "111 mL is correct for the 50% solution.",
  },
  {
    id: 1374,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q15. In a cleanroom, what is the minimum air change per hour (ACH) typically required for an ISO 7 (Grade C) area?",
    options: ["5-10 ACH", "20-40 ACH", "100-150 ACH", "200-300 ACH"],
    correct: "20-40 ACH",
    explanation: "ISO 7 / Grade C areas commonly require about 20 to 40 air changes per hour.",
    explainCorrect: "20-40 ACH is correct.",
  },
  {
    id: 1375,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q16. A suspension contains 250 mg of drug per 5 mL. How many mL are needed for a 375 mg dose?",
    options: ["5.0 mL", "6.5 mL", "7.5 mL", "10.0 mL"],
    correct: "7.5 mL",
    explanation: "The concentration is 50 mg/mL, so 375 mg requires 7.5 mL.",
    explainCorrect: "7.5 mL is correct.",
  },
  {
    id: 1376,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q17. What does CAPA stand for?",
    options: [
      "Chemical and Physical Analysis",
      "Corrective and Preventive Action",
      "Control of Active Pharmaceutical Agents",
      "Cleaning and Packaging Audit",
    ],
    correct: "Corrective and Preventive Action",
    explanation: "CAPA is a quality system for correcting deviations and preventing recurrence.",
    explainCorrect: "Corrective and Preventive Action is correct.",
  },
  {
    id: 1377,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q18. A 10 mL vial contains 1 g of drug as dry powder. It is reconstituted to a final volume of 10 mL. What is the final concentration in mg/mL?",
    options: ["50 mg/mL", "100 mg/mL", "108.7 mg/mL", "1000 mg/mL"],
    correct: "100 mg/mL",
    explanation: "1 g is 1000 mg, and 1000 mg in 10 mL gives 100 mg/mL.",
    explainCorrect: "100 mg/mL is correct.",
  },
  {
    id: 1378,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q19. Which of the following is NOT a critical process parameter in tablet compression?",
    options: ["Compression force", "Tablet weight", "Colour of the granule", "Tablet hardness"],
    correct: "Colour of the granule",
    explanation: "Colour is an appearance attribute, not a critical process parameter for tablet performance.",
    explainCorrect: "Colour of the granule is the exception.",
  },
  {
    id: 1379,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q20. A 500 mL bag of IV fluid is to be infused over 4 hours. The drop factor is 20 drops/mL. Calculate drops per minute.",
    options: ["21 drops/min", "31 drops/min", "42 drops/min", "62 drops/min"],
    correct: "42 drops/min",
    explanation: "500 mL over 4 hours is 125 mL/hour. At 20 drops/mL, this is about 42 drops/min.",
    explainCorrect: "42 drops/min is correct.",
  },
  {
    id: 1380,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q21. What is the first action if a differential pressure alarm sounds in an aseptic manufacturing suite?",
    options: ["Ignore it and finish the batch", "Stop production and investigate", "Increase the fan speed manually", "Document it after the shift"],
    correct: "Stop production and investigate",
    explanation: "A pressure alarm may indicate loss of contamination control, so production should stop until the issue is investigated.",
    explainCorrect: "Stop production and investigate is correct.",
  },
  {
    id: 1381,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q22. What volume of a 1% w/v solution is required to make 300 mL of a 0.02% w/v solution?",
    options: ["2 mL", "4 mL", "6 mL", "8 mL"],
    correct: "6 mL",
    explanation: "Using C1V1 = C2V2 gives 1% x V1 = 0.02% x 300 mL, so V1 = 6 mL.",
    explainCorrect: "6 mL is correct.",
  },
  {
    id: 1382,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q23. What is the maximum allowable number of colony-forming units (CFU) in a Grade C (ISO 7) area during dynamic operation under EU GMP?",
    options: ["0 CFU", "10 CFU", "50 CFU", "100 CFU"],
    correct: "100 CFU",
    explanation: "EU GMP Grade C dynamic limits are commonly stated as 100 CFU per cubic meter for air monitoring.",
    explainCorrect: "100 CFU is correct.",
  },
  {
    id: 1383,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q24. A patient receives 2 L of IV fluid over 24 hours. What is the rate in mL/hour?",
    options: ["48 mL/h", "72 mL/h", "83.3 mL/h", "120 mL/h"],
    correct: "83.3 mL/h",
    explanation: "2000 mL divided by 24 hours is 83.3 mL/hour.",
    explainCorrect: "83.3 mL/h is correct.",
  },
  {
    id: 1384,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q25. What is the primary purpose of a media fill (process simulation) in aseptic manufacturing?",
    options: [
      "To test the nutrient content of the media",
      "To validate the aseptic filling process using growth medium instead of product",
      "To clean the filling line",
      "To test the colour of the final product",
    ],
    correct: "To validate the aseptic filling process using growth medium instead of product",
    explanation: "Media fills simulate aseptic processing with sterile growth medium to check for contamination risk.",
    explainCorrect: "Validating the aseptic filling process is correct.",
  },
  {
    id: 1385,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q26. How many milligrams of drug are in 2.5 mL of a 1:2000 w/v solution?",
    options: ["0.625 mg", "1.25 mg", "2.5 mg", "12.5 mg"],
    correct: "1.25 mg",
    explanation: "A 1:2000 solution contains 0.5 mg/mL, so 2.5 mL contains 1.25 mg.",
    explainCorrect: "1.25 mg is correct.",
  },
  {
    id: 1386,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q27. Which of the following best describes qualification in GMP?",
    options: [
      "Proving equipment works correctly as installed and operates as intended",
      "Checking finished products",
      "Writing SOPs",
      "Hiring qualified staff",
    ],
    correct: "Proving equipment works correctly as installed and operates as intended",
    explanation: "Qualification is part of validation and covers installation, operation, and performance of equipment or systems.",
    explainCorrect: "The equipment qualification option is correct.",
  },
  {
    id: 1387,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q28. A formula for 200 g of ointment requires 10 g of active ingredient. How much active is needed for 50 g?",
    options: ["1.5 g", "2.0 g", "2.5 g", "5.0 g"],
    correct: "2.5 g",
    explanation: "10 g in 200 g scales to 2.5 g in 50 g.",
    explainCorrect: "2.5 g is correct.",
  },
  {
    id: 1388,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q29. In aseptic processing, a single colony-forming unit (CFU) detected in a media fill is classified as:",
    options: [
      "Acceptable if only one unit",
      "A critical deviation leading to validation failure",
      "A minor observation",
      "Only reportable if more than 10 CFU",
    ],
    correct: "A critical deviation leading to validation failure",
    explanation: "Any microbial growth in a media fill means the simulation has failed and must be investigated.",
    explainCorrect: "A critical deviation leading to validation failure is correct.",
  },
  {
    id: 1389,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q30. What is the percentage strength w/w of a solution containing 15 g of solute in 250 g of solution?",
    options: ["2%", "4%", "6%", "8%"],
    correct: "6%",
    explanation: "15 divided by 250 times 100 equals 6% w/w.",
    explainCorrect: "6% w/w is correct.",
  },
  {
    id: 1390,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q31. Who is ultimately responsible for GMP compliance in a pharmaceutical manufacturing facility in Ghana?",
    options: ["Quality Control manager", "Production manager", "Responsible Pharmacist", "Machine operator"],
    correct: "Responsible Pharmacist",
    explanation: "The responsible pharmacist holds the primary legal and professional responsibility for GMP compliance in this setting.",
    explainCorrect: "Responsible Pharmacist is correct.",
  },
  {
    id: 1391,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q32. A child weighing 18 kg requires 5 mg/kg of drug. The syrup is 25 mg/5 mL. How many mL per dose?",
    options: ["3.6 mL", "5.0 mL", "12.5 mL", "18.0 mL"],
    correct: "18.0 mL",
    explanation: "The dose is 90 mg. Since the syrup is 5 mg/mL, 90 mg requires 18 mL.",
    explainCorrect: "18.0 mL is correct.",
  },
  {
    id: 1392,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q33. What does RABS stand for in sterile manufacturing?",
    options: [
      "Rapid Aseptic Barrier System",
      "Restricted Access Barrier System",
      "Recycled Air Barrier System",
      "Robotic Aseptic Blow-Fill-Seal",
    ],
    correct: "Restricted Access Barrier System",
    explanation: "RABS is a barrier technology used to reduce contamination risk in aseptic processing.",
    explainCorrect: "Restricted Access Barrier System is correct.",
  },
  {
    id: 1393,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q34. A patient requires 800 mg of drug. Tablets are 400 mg each. How many tablets?",
    options: ["1 tablet", "2 tablets", "3 tablets", "4 tablets"],
    correct: "2 tablets",
    explanation: "800 mg divided by 400 mg per tablet equals 2 tablets.",
    explainCorrect: "2 tablets is correct.",
  },
  {
    id: 1394,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q35. Which of the following is a critical environmental parameter to monitor in a cleanroom?",
    options: ["Colour of the walls", "Differential pressure", "Number of windows", "Type of light bulbs"],
    correct: "Differential pressure",
    explanation: "Differential pressure helps maintain directional airflow from cleaner to less clean areas.",
    explainCorrect: "Differential pressure is correct.",
  },
  {
    id: 1395,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q36. How many grams of active ingredient are in 2.5 L of a 0.2% w/v solution?",
    options: ["0.5 g", "2.5 g", "5.0 g", "25 g"],
    correct: "5.0 g",
    explanation: "0.2% w/v is 0.2 g per 100 mL, so 2500 mL contains 5 g.",
    explainCorrect: "5.0 g is correct.",
  },
  {
    id: 1396,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q37. What is the correct action if a batch record shows an unexplained deviation?",
    options: [
      "Ignore it if the final product passes tests",
      "Destroy the batch immediately",
      "Investigate under the CAPA system",
      "Continue production and document later",
    ],
    correct: "Investigate under the CAPA system",
    explanation: "Any unexplained deviation must be investigated so the root cause can be identified and corrected.",
    explainCorrect: "Investigate under the CAPA system is correct.",
  },
  {
    id: 1397,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q38. Using C1V1 = C2V2, how many mL of 10% w/v stock are needed to prepare 200 mL of 0.5% w/v?",
    options: ["5 mL", "10 mL", "15 mL", "20 mL"],
    correct: "10 mL",
    explanation: "10% x V1 = 0.5% x 200, so V1 is 10 mL.",
    explainCorrect: "10 mL is correct.",
  },
  {
    id: 1398,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q39. Blow-Fill-Seal (BFS) technology is primarily used to manufacture:",
    options: [
      "Dry powder inhalers",
      "Sterile unit-dose liquid products (e.g., eye drops, nebuliser solutions)",
      "Transdermal patches",
      "Hard gelatin capsules",
    ],
    correct: "Sterile unit-dose liquid products (e.g., eye drops, nebuliser solutions)",
    explanation: "BFS forms, fills, and seals plastic containers in one sterile process, which is ideal for unit-dose liquids.",
    explainCorrect: "Sterile unit-dose liquid products is correct.",
  },
  {
    id: 1399,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q40. A patient is prescribed 125 mg of a drug. The available liquid is 250 mg/5 mL. What volume is required?",
    options: ["1.5 mL", "2.0 mL", "2.5 mL", "3.0 mL"],
    correct: "2.5 mL",
    explanation: "The liquid contains 50 mg/mL, so 125 mg requires 2.5 mL.",
    explainCorrect: "2.5 mL is correct.",
  },
  {
    id: 1400,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q41. Which of the following requires mandatory validation?",
    options: [
      "Cleaning of office floors",
      "Sterilization cycle of an autoclave",
      "Packaging of non-sterile tablets",
      "Storage of printed labels",
    ],
    correct: "Sterilization cycle of an autoclave",
    explanation: "Sterilization is a critical process and the autoclave cycle must be validated.",
    explainCorrect: "Sterilization cycle of an autoclave is correct.",
  },
  {
    id: 1401,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q42. A 500 mg tablet is produced. The average weight is 620 mg. What is the percentage of active ingredient w/w?",
    options: ["60.6%", "70.7%", "80.6%", "90.7%"],
    correct: "80.6%",
    explanation: "500 divided by 620 times 100 is about 80.65%.",
    explainCorrect: "80.6% is the closest correct value.",
  },
  {
    id: 1402,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q43. In a quality control lab, an expired reference standard is found. What should you do?",
    options: [
      "Use it if stored properly",
      "Discard and quarantine any tests that used it",
      "Use it but note the expiry in the report",
      "Ignore it if results look fine",
    ],
    correct: "Discard and quarantine any tests that used it",
    explanation: "Expired standards may give inaccurate results, so any tests run with them should be quarantined and repeated.",
    explainCorrect: "Discard and quarantine any tests that used it is correct.",
  },
  {
    id: 1403,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q44. A patient needs 2.5 mg of a drug. The injection is 10 mg/mL. What volume?",
    options: ["0.1 mL", "0.25 mL", "0.5 mL", "1.0 mL"],
    correct: "0.25 mL",
    explanation: "2.5 mg divided by 10 mg/mL equals 0.25 mL.",
    explainCorrect: "0.25 mL is correct.",
  },
  {
    id: 1404,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q45. What is the primary purpose of a Quality Risk Management (QRM) system?",
    options: [
      "To eliminate all risks completely",
      "To identify, evaluate, and control risks to product quality",
      "To reduce production costs at any expense",
      "To replace validation requirements",
    ],
    correct: "To identify, evaluate, and control risks to product quality",
    explanation: "QRM is a structured way to manage quality risks, not eliminate risk entirely.",
    explainCorrect: "Identifying, evaluating, and controlling quality risks is correct.",
  },
  {
    id: 1405,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q46. A 100 mL infusion contains 400 mg of lidocaine. The rate is 20 mL/hour. How many mg per hour?",
    options: ["40 mg/h", "80 mg/h", "100 mg/h", "200 mg/h"],
    correct: "80 mg/h",
    explanation: "The concentration is 4 mg/mL, so 20 mL/hour delivers 80 mg/hour.",
    explainCorrect: "80 mg/h is correct.",
  },
  {
    id: 1406,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q47. Which of the following is NOT a requirement for personnel entering a Grade B cleanroom?",
    options: [
      "No makeup or jewellery",
      "Full sterile gowning including gloves and mask",
      "Street clothes allowed under the gown",
      "Hand washing before gowning",
    ],
    correct: "Street clothes allowed under the gown",
    explanation: "Personnel must wear cleanroom clothing; street clothes are not permitted under the gown.",
    explainCorrect: "Street clothes allowed under the gown is the exception.",
  },
  {
    id: 1407,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q48. Using alligation, how many parts of 70% alcohol and 20% alcohol are needed to make 40% alcohol?",
    options: ["2 parts 70%, 3 parts 20%", "3 parts 70%, 2 parts 20%", "4 parts 70%, 1 part 20%", "1 part 70%, 4 parts 20%"],
    correct: "2 parts 70%, 3 parts 20%",
    explanation: "The alligation ratio is 20 parts from the strong solution and 30 parts from the weak solution, which simplifies to 2:3.",
    explainCorrect: "2 parts of 70% and 3 parts of 20% is correct.",
  },
  {
    id: 1408,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q49. What is the maximum allowable holding time for a cleaned piece of equipment before use?",
    options: [
      "24 hours exactly",
      "1 week",
      "Defined by a validated holding time study",
      "No limit if covered with plastic",
    ],
    correct: "Defined by a validated holding time study",
    explanation: "Cleaned equipment holding time must be established and justified through validation.",
    explainCorrect: "Defined by a validated holding time study is correct.",
  },
  {
    id: 1409,
    type: "single",
    category: "Manufacturing and Calculation",
    question: "Q50. A patient receives 0.5 L of IV fluid over 8 hours. Calculate the rate in mL/hour.",
    options: ["40.5 mL/h", "50.0 mL/h", "62.5 mL/h", "75.0 mL/h"],
    correct: "62.5 mL/h",
    explanation: "500 mL divided by 8 hours equals 62.5 mL/hour.",
    explainCorrect: "62.5 mL/h is correct.",
  },
];
