export const fourthBatchQuestions = [
  {
    id: 1004,
    type: "single",
    category: "Gastrointestinal Disorders",
    question: "Q1. Long term use of PPIs could cause all the following except?",
    options: ["Bone fractures", "Mendelson syndrome", "Clostridium difficile infection", "Macrocytic anaemia"],
    correct: "Mendelson syndrome",
    explanation: "Long-term proton pump inhibitor use is linked with bone loss, enteric infections, and vitamin B12 deficiency, but not Mendelson syndrome.",
    explainCorrect: "Mendelson syndrome is the exception because it is aspiration pneumonitis, not a known chronic PPI adverse effect.",
  },
  {
    id: 1005,
    type: "single",
    category: "Gastrointestinal Disorders",
    question: "Q2. All the following are gastric cytoprotective agents except?",
    options: ["Cholestyramine", "Misoprostol", "Simethicone", "Sucralfate"],
    correct: "Cholestyramine",
    explanation: "Misoprostol and sucralfate protect the gastric mucosa, and simethicone is an antiflatulent; cholestyramine is a bile acid sequestrant.",
    explainCorrect: "Cholestyramine is the exception because it is not a gastric cytoprotective agent.",
  },
  {
    id: 1006,
    type: "single",
    category: "Infectious Diseases",
    question: "Q3. Which of these viruses is most likely to cause only acute hepatitis?",
    options: ["Hepatitis D", "Hepatitis C", "Hepatitis A", "Hepatitis B"],
    correct: "Hepatitis A",
    explanation: "Hepatitis A usually causes an acute, self-limiting infection rather than chronic hepatitis.",
    explainCorrect: "Hepatitis A is the best answer because it classically causes only acute hepatitis.",
  },
  {
    id: 1007,
    type: "single",
    category: "Infectious Diseases",
    question: "Q4. Infection with this virus does not occur unless in the presence of Hepatitis B?",
    options: ["Hepatitis C", "Hepatitis A", "Hepatitis E", "Hepatitis D"],
    correct: "Hepatitis D",
    explanation: "Hepatitis D is a defective virus that requires Hepatitis B surface antigen for replication.",
    explainCorrect: "Hepatitis D depends on Hepatitis B, so it cannot occur without HBV.",
  },
  {
    id: 1008,
    type: "single",
    category: "Infectious Diseases",
    question: "Q5. Which of these viruses is transmitted via the faecal-oral route?",
    options: ["Hepatitis A", "Hepatitis C", "Hepatitis D", "Hepatitis B"],
    correct: "Hepatitis A",
    explanation: "Hepatitis A spreads mainly by the faecal-oral route through contaminated food or water.",
    explainCorrect: "Hepatitis A is the faecal-oral hepatitis virus listed here.",
  },
  {
    id: 1009,
    type: "single",
    category: "Infectious Diseases",
    question: "Q6. All the following do not have globally approved vaccines except?",
    options: ["Hepatitis D", "Hepatitis A", "Hepatitis E", "Hepatitis C"],
    correct: "Hepatitis A",
    explanation: "A widely used and globally approved vaccine exists for Hepatitis A, while the others do not have broad global vaccine approval in routine use.",
    explainCorrect: "Hepatitis A is the exception because a global vaccine is available.",
  },
  {
    id: 1010,
    type: "single",
    category: "Infectious Diseases",
    question: "Q7. All the following are true about use of peginterferon alfa for Hepatitis B except?",
    options: ["Can cause flu-like syndrome", "Relapse is frequent", "Has a low response rate of 30-40%", "Ideal for patients with decompensated liver cirrhosis"],
    correct: "Ideal for patients with decompensated liver cirrhosis",
    explanation: "Peginterferon can cause flu-like effects and has modest response rates, but it is not ideal in decompensated liver disease.",
    explainCorrect: "Decompensated liver cirrhosis is the exception because peginterferon is generally avoided in such patients.",
  },
  {
    id: 1011,
    type: "single",
    category: "Infectious Diseases",
    question: "Q8. All the following are recommended for Hepatitis B treatment in a patient with decompensated liver disease except?",
    options: ["Tenofovir", "Entecavir", "Lamivudine and Adefovir", "Pegasys"],
    correct: "Pegasys",
    explanation: "Tenofovir and entecavir are preferred options, while peginterferon is generally avoided in decompensated liver disease.",
    explainCorrect: "Pegasys is the exception because interferon-based therapy is not recommended in decompensated liver disease.",
  },
  {
    id: 1012,
    type: "single",
    category: "Infectious Diseases",
    question: "Q9. Recommended treatment regimen for a patient with HIV/Hepatitis B coinfection?",
    options: ["TAF", "TDF", "TDF + 3TC + DTG", "TAF + 3TC + DTG"],
    correct: "TDF + 3TC + DTG",
    explanation: "A regimen containing two agents active against HBV, plus an HIV anchor drug, is the usual approach in HIV/HBV coinfection.",
    explainCorrect: "TDF + 3TC + DTG fits the expected HIV/HBV coinfection regimen best among the options.",
  },
  {
    id: 1013,
    type: "single",
    category: "Infectious Diseases",
    question: "Q10. HBsAg+, anti-HBs-, anti-HBc IgM+ indicates?",
    options: ["Immunity from past infection", "Chronic infection", "Recently vaccinated", "Acute infection"],
    correct: "Acute infection",
    explanation: "HBsAg positivity with anti-HBc IgM positivity is the classic serologic pattern for acute Hepatitis B.",
    explainCorrect: "This marker pattern indicates acute Hepatitis B infection.",
  },
  {
    id: 1014,
    type: "single",
    category: "Infectious Diseases",
    question: "Q11. HBsAg-, anti-HBs+, anti-HBc IgM- indicates?",
    options: ["Immunity from past infection", "Chronic infection", "Recently vaccinated", "Acute infection"],
    correct: "Recently vaccinated",
    explanation: "Anti-HBs positivity without anti-HBc usually suggests immunity from vaccination rather than past infection.",
    explainCorrect: "Recently vaccinated is the intended answer for this serology pattern.",
  },
  {
    id: 1015,
    type: "single",
    category: "Infectious Diseases",
    question: "Q12. HBsAg+, anti-HBs-, anti-HBc IgM-, anti-HBc IgG+ indicates?",
    options: ["Immunity from past infection", "Chronic infection", "Recently vaccinated", "Acute infection"],
    correct: "Chronic infection",
    explanation: "Persistence of HBsAg with IgG core antibody and no anti-HBs is typical of chronic Hepatitis B infection.",
    explainCorrect: "The pattern indicates chronic HBV infection.",
  },
  {
    id: 1016,
    type: "single",
    category: "Infectious Diseases",
    question: "Q13. HBsAg-, anti-HBs+, anti-HBc+ indicates?",
    options: ["Immunity from past infection", "Chronic infection", "Recently vaccinated", "Acute infection"],
    correct: "Immunity from past infection",
    explanation: "Anti-HBs and anti-HBc together indicate past natural infection with recovery.",
    explainCorrect: "Immunity from past infection is the correct interpretation.",
  },
  {
    id: 1017,
    type: "single",
    category: "Infectious Diseases",
    question: "Q14. Used in monitoring efficacy of antiviral therapy in hepatitis B?",
    options: ["HBeAg", "HBsAg", "HBV DNA", "Anti-HBc"],
    correct: "HBV DNA",
    explanation: "HBV DNA best reflects viral replication and treatment response in hepatitis B.",
    explainCorrect: "HBV DNA is the preferred marker for monitoring antiviral efficacy.",
  },
  {
    id: 1018,
    type: "single",
    category: "Infectious Diseases",
    question: "Q15. This marker cannot be quantitatively determined using serology test?",
    options: ["HBeAg", "HBcAg", "HBsAg", "Anti-HBc"],
    correct: "HBcAg",
    explanation: "HBcAg is not a circulating serum marker and is therefore not quantitated by routine serology.",
    explainCorrect: "HBcAg is the exception because it is not measured as a serum serology marker.",
  },
  {
    id: 1019,
    type: "single",
    category: "Infectious Diseases",
    question: "Q16. All these are possible explanations for a patient with HBsAg-, anti-HBs-, and anti-HBc+ except?",
    options: ["Might be recovering from an acute infection", "False positive anti-HBc", "Undetectable levels of HBsAg in chronic infection", "Recently vaccinated"],
    correct: "Recently vaccinated",
    explanation: "A patient with isolated anti-HBc can be recovering, have false positivity, or have occult infection, but recent vaccination would usually produce anti-HBs.",
    explainCorrect: "Recently vaccinated is the exception because vaccination alone should not leave isolated anti-HBc.",
  },
  {
    id: 1020,
    type: "single",
    category: "Infectious Diseases",
    question: "Q17. All these factors influence whether to initiate treatment for hepatitis B except?",
    options: ["Presence or absence of cirrhosis", "ALT levels", "HBV DNA levels", "IgG and IgM levels"],
    correct: "IgG and IgM levels",
    explanation: "Treatment decisions depend on liver damage and viral replication markers, not routine total IgG/IgM levels.",
    explainCorrect: "IgG and IgM levels are the exception because they are not standard treatment-start criteria.",
  },
  {
    id: 1021,
    type: "single",
    category: "Infectious Diseases",
    question: "Q18. Which of these signifies active infection or active replication of the hepatitis B virus?",
    options: ["HBsAg", "HBeAg", "Anti-HBc IgG", "Anti-HBc IgM"],
    correct: "HBeAg",
    explanation: "HBeAg is a marker of active viral replication and high infectivity in hepatitis B.",
    explainCorrect: "HBeAg is the best marker of active replication in this question.",
  },
  {
    id: 1022,
    type: "single",
    category: "Infectious Diseases",
    question: "Q19. Recovery from hepatitis B infection is denoted by the following except?",
    options: ["Seroconversion from HBsAg to anti-HBs", "Seroconversion from HBeAg to anti-HBe", "Seroconversion from HBcAg to anti-HBc", "Normalisation of ALT levels"],
    correct: "Seroconversion from HBcAg to anti-HBc",
    explanation: "Recovery is associated with loss of surface or e antigen and normalization of liver enzymes, while HBcAg is not a routine serum seroconversion marker.",
    explainCorrect: "HBcAg to anti-HBc is the exception because core antigen is not the usual recovery serology marker.",
  },
  {
    id: 1023,
    type: "single",
    category: "Infectious Diseases",
    question: "Q20. In the window period of hepatitis B infection, which marker is used in the diagnosis of the infection?",
    options: ["HBsAg", "HBeAg", "Anti-HBc IgM", "Anti-HBe"],
    correct: "Anti-HBc IgM",
    explanation: "During the window period, anti-HBc IgM may be the only positive serologic marker.",
    explainCorrect: "Anti-HBc IgM is the correct marker in the HBV window period.",
  },
  {
    id: 1024,
    type: "single",
    category: "Rheumatology & Pain",
    question: "Q21. Presence of this autoantibody signify drug induced lupus erythematosus?",
    options: ["Anti nuclear antibody", "Anti dsDNA", "Anti Sm antibody", "Anti histone antibody"],
    correct: "Anti histone antibody",
    explanation: "Drug-induced lupus is classically associated with anti-histone antibodies.",
    explainCorrect: "Anti-histone antibody is the marker most associated with drug-induced lupus.",
  },
  {
    id: 1025,
    type: "single",
    category: "Neurology & Psychiatry",
    question: "Q22. Rationale for giving initial 300mg aspirin in acute stroke?",
    options: ["To acetylate already aggregated platelets", "To provide anti inflammatory effect", "To prevent new platelets from aggregating", "To provide analgesic and antipyretic effect"],
    correct: "To prevent new platelets from aggregating",
    explanation: "Aspirin irreversibly inhibits platelet cyclooxygenase, reducing further platelet aggregation after ischemic stroke.",
    explainCorrect: "The goal is to stop fresh platelets from aggregating at the thrombus site.",
  },
  {
    id: 1026,
    type: "single",
    category: "Neurology & Psychiatry",
    question: "Q23. Rationale for giving nimodipine in haemorrhagic stroke?",
    options: ["To reduce the elevated blood pressure in acute stroke", "To prevent delayed cerebral ischaemia from vasospasms", "To reduce cerebral perfusion pressure", "To reduce intracranial pressure"],
    correct: "To prevent delayed cerebral ischaemia from vasospasms",
    explanation: "Nimodipine is used after subarachnoid haemorrhage to reduce vasospasm-related delayed ischemia.",
    explainCorrect: "Nimodipine helps prevent delayed cerebral ischaemia from vasospasm.",
  },
  {
    id: 1027,
    type: "single",
    category: "Neurology & Psychiatry",
    question: "Q24. The benefit of nimodipine therapy is in which type of haemorrhagic stroke?",
    options: ["Subdural haematoma", "Intracerebral haemorrhage", "Subarachnoid haemorrhage", "Epidural haemorrhage"],
    correct: "Subarachnoid haemorrhage",
    explanation: "Nimodipine is specifically beneficial after aneurysmal subarachnoid haemorrhage.",
    explainCorrect: "Subarachnoid haemorrhage is the haemorrhagic stroke where nimodipine is beneficial.",
  },
  {
    id: 1028,
    type: "single",
    category: "Neurology & Psychiatry",
    question: "Q25. When is it appropriate to initiate nimodipine therapy after onset of hemorrhagic stroke?",
    options: ["Within 4.5 hrs", "Within 96hrs", "Within 24hrs", "After 7 days"],
    correct: "Within 96hrs",
    explanation: "Nimodipine should be started early after subarachnoid haemorrhage, typically within the first 4 days.",
    explainCorrect: "Within 96 hours is the intended start window for nimodipine therapy.",
  },
  {
    id: 1029,
    type: "single",
    category: "Neurology & Psychiatry",
    question: "Q26. How long should nimodipine therapy be given for?",
    options: ["14 days", "4 days", "21 days", "30 days"],
    correct: "21 days",
    explanation: "The usual course of nimodipine after subarachnoid haemorrhage is 21 days.",
    explainCorrect: "21 days is the standard duration in this question set.",
  },
  {
    id: 1030,
    type: "single",
    category: "Neurology & Psychiatry",
    question: "Q27. All these are true about nimodipine except?",
    options: ["Nimodipine is a dihydropyridine calcium channel blocker", "Nimodipine is highly hydrophilic", "It has a short half life of 1-2 hrs", "Requires dose reduction in severe liver impairment"],
    correct: "Nimodipine is highly hydrophilic",
    explanation: "Nimodipine is a lipophilic dihydropyridine with a short half-life and hepatic dose considerations.",
    explainCorrect: "Highly hydrophilic is the false statement here.",
  },
  {
    id: 1031,
    type: "single",
    category: "Neurology & Psychiatry",
    question: "Q28. All these are true about IV mannitol except?",
    options: ["Mannitol is a diuretic", "It can cause a rebound increase in intracranial pressure", "It has a reflection coefficient of 0.9", "It should be avoided in peptic ulcer patients"],
    correct: "It should be avoided in peptic ulcer patients",
    explanation: "Mannitol is an osmotic diuretic and can rebound if overused, but peptic ulcer disease is not the usual contraindication highlighted in this question.",
    explainCorrect: "Peptic ulcer patients are the exception because that is not a standard mannitol avoidance rule.",
  },
  {
    id: 1032,
    type: "single",
    category: "Neurology & Psychiatry",
    question: "Q29. Why mannitol should not be administered with blood?",
    options: ["It can cause haemolysis of red blood cells", "It can cause sickling of red blood cells", "It can cause crenation of red blood cells", "It can cause plasmolysis of red blood cells"],
    correct: "It can cause haemolysis of red blood cells",
    explanation: "Mannitol is highly hyperosmolar and should not be mixed with blood products because of red cell damage concerns.",
    explainCorrect: "Haemolysis is the intended reason in this item.",
  },
  {
    id: 1033,
    type: "single",
    category: "Neurology & Psychiatry",
    question: "Q30. A patient needs 250ml 3% hypertonic saline for intracranial pressure. However, you do not have 3% hypertonic saline available. Which infusion can be used to prepare the 3% hypertonic saline using alligation?",
    options: ["Ringers lactate and normal saline", "7% hypertonic saline and 20% hypertonic saline", "Water for injection and normal saline", "Normal saline and 20% hypertonic saline"],
    correct: "Normal saline and 20% hypertonic saline",
    explanation: "Alligation for 3% saline uses a low-concentration saline base and a high-concentration hypertonic saline stock.",
    explainCorrect: "Normal saline and 20% hypertonic saline are the correct pair among the options.",
  },
  {
    id: 1034,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q31. All these are cardioembolic causes of stroke except?",
    options: ["Heart failure", "Atherosclerosis", "Atrial fibrillation", "Endocarditis"],
    correct: "Atherosclerosis",
    explanation: "Atrial fibrillation, heart failure, and endocarditis can cause embolic stroke, while atherosclerosis is primarily a vascular source.",
    explainCorrect: "Atherosclerosis is the exception because it is not a cardioembolic source.",
  },
  {
    id: 1035,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q32. All the following are used in managing intermittent claudication in peripheral artery disease except?",
    options: ["Naftidrofuryl oxalate", "Pentoxifylline", "Ranolazine", "Cilostazol"],
    correct: "Ranolazine",
    explanation: "Naftidrofuryl, pentoxifylline, and cilostazol are used for claudication, while ranolazine is an antianginal drug.",
    explainCorrect: "Ranolazine is the exception because it is not a standard intermittent claudication treatment.",
  },
  {
    id: 1036,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q33. Which of these beta blockers is not recommended for use in heart failure?",
    options: ["Metoprolol tartrate", "Carvedilol", "Bisoprolol", "Metoprolol succinate"],
    correct: "Metoprolol tartrate",
    explanation: "Evidence-based heart failure beta blockers include carvedilol, bisoprolol, and metoprolol succinate, not metoprolol tartrate.",
    explainCorrect: "Metoprolol tartrate is the exception because the succinate formulation is the preferred HF option.",
  },
  {
    id: 1037,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q34. All the following are true about digoxin in heart failure patients except?",
    options: ["It can cause green-yellow vision", "It improves survival in heart failure patients", "Ideal for patients with heart failure and atrial fibrillation", "It has a negative chronotropic effect"],
    correct: "It improves survival in heart failure patients",
    explanation: "Digoxin improves symptoms and rate control but does not improve overall survival in heart failure.",
    explainCorrect: "Improves survival is the false statement here.",
  },
  {
    id: 1038,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q35. The amount of air that can forcibly be exhaled in one second is referred to as?",
    options: ["Vital capacity", "Forced vital capacity", "Forced expiratory volume in one second", "Peak expiratory volume"],
    correct: "Forced expiratory volume in one second",
    explanation: "FEV1 is the amount of air exhaled during the first second of a forced expiration.",
    explainCorrect: "Forced expiratory volume in one second is the correct term.",
  },
  {
    id: 1039,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q36. Maximum volume of air exhaled after taking a deep breath in?",
    options: ["Vital capacity", "Forced vital capacity", "Forced expiratory volume in one second", "Peak expiratory volume"],
    correct: "Vital capacity",
    explanation: "Vital capacity is the maximum amount of air exhaled after a maximal inspiration.",
    explainCorrect: "Vital capacity is the best answer for this lung volume definition.",
  },
  {
    id: 1040,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q37. All the following are true about dry powder inhalers except?",
    options: ["Delivers medication in a powdered form", "Requires no propellant", "Requires the use of spacers", "Does not require shaking prior to use"],
    correct: "Requires the use of spacers",
    explanation: "Dry powder inhalers do not use spacers; they rely on the patient's inspiratory effort.",
    explainCorrect: "Requires spacers is the false statement here.",
  },
  {
    id: 1041,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q38. Which of these inhalers can be used as both controller and reliever?",
    options: ["Pulmicort inhaler", "Symbicort inhaler", "Seretide inhaler", "Ventolin inhaler"],
    correct: "Symbicort inhaler",
    explanation: "Symbicort contains budesonide and formoterol and is used in maintenance-and-reliever therapy.",
    explainCorrect: "Symbicort is the combined controller/reliever inhaler in this list.",
  },
  {
    id: 1042,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q39. All the following are controllers in asthma management except?",
    options: ["Ipratropium inhaler", "Salmeterol inhaler", "Fluticasone inhaler", "Montelukast"],
    correct: "Ipratropium inhaler",
    explanation: "Controller drugs include inhaled corticosteroids, LABAs, and leukotriene modifiers; ipratropium is not a standard controller.",
    explainCorrect: "Ipratropium inhaler is the exception.",
  },
  {
    id: 1043,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q40. Preferred mainstay agent in asthma management?",
    options: ["Short acting beta 2 agonists", "Long acting beta 2 agonists", "Inhaled corticosteroids", "Long acting muscarinic antagonists"],
    correct: "Inhaled corticosteroids",
    explanation: "Inhaled corticosteroids are the mainstay controller therapy for persistent asthma.",
    explainCorrect: "Inhaled corticosteroids are the preferred mainstay agent.",
  },
  {
    id: 1044,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q41. All these are side effects of salbutamol inhaler except?",
    options: ["Tremors", "Hyperkalemia", "Palpitation", "Hyperglycemia"],
    correct: "Hyperkalemia",
    explanation: "Salbutamol can cause tremor, palpitations, hypokalemia, and sometimes hyperglycemia, but not hyperkalemia.",
    explainCorrect: "Hyperkalemia is the exception because salbutamol more commonly lowers potassium.",
  },
  {
    id: 1045,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q42. Rationale for rinsing the mouth after using inhaled corticosteroids?",
    options: ["To augment the efficacy of the drug", "To prevent halitosis", "To prevent oral candidiasis", "To prevent tooth decay"],
    correct: "To prevent oral candidiasis",
    explanation: "Rinsing removes residual steroid from the mouth and reduces the risk of oral thrush.",
    explainCorrect: "Oral candidiasis prevention is the main reason for mouth rinsing.",
  },
  {
    id: 1046,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q43. Rationale for using spacers in asthma management include all except?",
    options: ["Allows more time for evaporation of the propellant so that a large proportion can be inhaled and deposited in the lungs", "Useful in children and in the elderly", "Removes the need for coordination between actuation and inhalation", "Increases the chances of oral candidiasis"],
    correct: "Increases the chances of oral candidiasis",
    explanation: "Spacers improve delivery and reduce local steroid deposition, so they do not increase oral candidiasis risk.",
    explainCorrect: "Increases the chances of oral candidiasis is the exception.",
  },
  {
    id: 1047,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q44. Which of these leukotriene modifying drugs inhibit the formation of leukotrienes through lipooxygenase inhibition?",
    options: ["Montelukast", "Zileuton", "Zafirlukast", "Melisma"],
    correct: "Zileuton",
    explanation: "Zileuton inhibits 5-lipoxygenase and blocks leukotriene synthesis.",
    explainCorrect: "Zileuton is the leukotriene synthesis inhibitor.",
  },
  {
    id: 1048,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q45. All the following agents can be used in exercise induced bronchospasm except?",
    options: ["Aminophylline", "Salmeterol", "Montelukast", "Salbutamol"],
    correct: "Aminophylline",
    explanation: "Salbutamol, salmeterol, and montelukast are used for prevention of exercise-induced bronchospasm, while aminophylline is not a preferred choice.",
    explainCorrect: "Aminophylline is the exception in this set.",
  },
  {
    id: 1049,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q46. A post bronchodilator FEV1/FVC < 0.7 confirms the diagnosis of?",
    options: ["COPD", "Pneumonia", "Asthma", "Pneumoconosis"],
    correct: "COPD",
    explanation: "A persistent post-bronchodilator FEV1/FVC ratio below 0.7 is diagnostic of COPD.",
    explainCorrect: "COPD is confirmed by a post-bronchodilator FEV1/FVC below 0.7.",
  },
  {
    id: 1050,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q47. All these are true about Asthma and COPD except?",
    options: ["Sputum production is more common in COPD than Asthma", "Airflow limitation is reversible in asthma but irreversible in COPD", "Bronchodilators are the preferred first line agents in both conditions", "Smoking history of more than 10 years is more associated with COPD than Asthma"],
    correct: "Bronchodilators are the preferred first line agents in both conditions",
    explanation: "Bronchodilators are central in COPD, but inhaled corticosteroids are the mainstay controller therapy in asthma.",
    explainCorrect: "That statement is the exception because it is not equally true for both diseases.",
  },
  {
    id: 1051,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q48. All these medications can trigger asthmatic attacks except?",
    options: ["Nebulised hypertonic saline", "Aspirin", "Nebulised mannitol", "Propranolol"],
    correct: "Propranolol",
    explanation: "The saline and mannitol aerosols are airway challenge agents and aspirin is a known trigger; propranolol is the intended odd one out in this set.",
    explainCorrect: "Propranolol is the intended exception in this question set.",
  },
  {
    id: 1052,
    type: "single",
    category: "Infectious Diseases",
    question: "Q49. The rational representation of cholera replacement fluid is?",
    options: ["1:4:5", "4.5:1", "5:4:1", "5:1:4"],
    correct: "4.5:1",
    explanation: "The exam set uses a cholera replacement-fluid compounding ratio based on a saline-to-bicarbonate representation.",
    explainCorrect: "4.5:1 is the intended answer for this compounding ratio question.",
  },
  {
    id: 1053,
    type: "single",
    category: "Infectious Diseases",
    question: "Q50. Which type of diarrhoea does cholera cause?",
    options: ["Secretory diarrhoea", "Osmotic diarrhoea", "Exudative diarrhoea", "Osmotic diarrhoea"],
    correct: "Secretory diarrhoea",
    explanation: "Cholera toxin drives chloride and water secretion into the gut lumen, producing secretory diarrhoea.",
    explainCorrect: "Cholera causes secretory diarrhoea.",
  },
  {
    id: 1054,
    type: "single",
    category: "Infectious Diseases",
    question: "Q51. All the following antimalarials can be dosed once daily except?",
    options: ["Artesunate-pyronaridine", "Artesunate-amodiaquine", "Artemether-lumefantrine", "Dihydroartemisin-piperaquine"],
    correct: "Artemether-lumefantrine",
    explanation: "Artemether-lumefantrine is dosed twice daily for 3 days, unlike the once-daily regimens listed with it.",
    explainCorrect: "Artemether-lumefantrine is the exception because it is not a once-daily regimen.",
  },
  {
    id: 1055,
    type: "single",
    category: "Infectious Diseases",
    question: "Q52. Which of these agents is used for radical cure?",
    options: ["Mefloquine", "Primaquine", "Quinine", "Hydroxychloroquine"],
    correct: "Primaquine",
    explanation: "Primaquine is used for radical cure of vivax and ovale malaria because it clears dormant hypnozoites.",
    explainCorrect: "Primaquine is the radical cure drug in this list.",
  },
  {
    id: 1056,
    type: "single",
    category: "Infectious Diseases",
    question: "Q53. Which of these malaria prophylaxis in travellers should be avoided in patients with psychiatric disorders?",
    options: ["Mefloquine", "Atovaquone-proguanil", "Doxycycline", "Primaquine"],
    correct: "Mefloquine",
    explanation: "Mefloquine can cause neuropsychiatric adverse effects and should be avoided in people with psychiatric illness.",
    explainCorrect: "Mefloquine is the prophylaxis agent to avoid in psychiatric disorders.",
  },
];
