const assertionReasonOptions = [
  "First Statement is True, Second Statement is True and is a correct explanation of the first",
  "First Statement is True, Second Statement is True but not a correct explanation of the first",
  "First Statement is True, Second Statement is False",
  "First Statement is False, second Statement is True",
  "Both Statements are False",
];

export const fifthBatchQuestions = [
  {
    id: 1057,
    type: "single",
    category: "Infectious Diseases",
    question: "Q1. The classic paroxysm of fever alternating with chills and diaphoresis in falciparum infected patients is termed?",
    options: ["Quotidian fever", "Benign tertian fever", "Malignant tertian fever", "Quartan fever"],
    correct: "Malignant tertian fever",
    explanation: "Plasmodium falciparum classically causes malignant tertian malaria.",
    explainCorrect: "Malignant tertian fever is the classic pattern associated with falciparum malaria.",
  },
  {
    id: 1058,
    type: "single",
    category: "Infectious Diseases",
    question: "Q2. Which of the following can neutralise bound tetanus toxin?",
    options: ["Tetanus toxoid", "Human tetanus immunoglobulin", "Equine anti-tetanus serum", "None of the above"],
    correct: "None of the above",
    explanation: "Once tetanospasmin is bound to nerve tissue, it cannot be neutralised by antitoxin.",
    explainCorrect: "None of the listed agents can neutralise toxin that has already bound to neural tissue.",
  },
  {
    id: 1059,
    type: "single",
    category: "Infectious Diseases",
    question: "Q3. All the following are tetanus-prone wounds except?",
    options: ["Puncture wounds", "Compound fractures", "Burn wounds lasting less than 6 hours before skin graft", "Dog bite wound"],
    correct: "Burn wounds lasting less than 6 hours before skin graft",
    explanation: "Tetanus-prone injuries are typically contaminated, deep, or devitalised wounds.",
    explainCorrect: "The burn wound described is the exception in this item.",
  },
  {
    id: 1060,
    type: "single",
    category: "Infectious Diseases",
    question: "Q4. All the following are goals of treatment in tetanus except?",
    options: ["Halting toxin production", "Neutralizing bound toxins", "Airway and supportive therapy", "Managing dysautonomia"],
    correct: "Neutralizing bound toxins",
    explanation: "Treatment targets unbound toxin, wound source control, supportive care, and autonomic instability.",
    explainCorrect: "Neutralizing bound toxins is not achievable, so it is the exception.",
  },
  {
    id: 1061,
    type: "single",
    category: "Infectious Diseases",
    question: "Q5. How many doses of tetanus toxoid is said to confer lifelong immunity?",
    options: ["10 doses", "3 doses", "5 doses", "None of the above"],
    correct: "5 doses",
    explanation: "A complete primary plus booster series is commonly taught as five doses for long-lasting protection.",
    explainCorrect: "Five doses is the intended answer in this set.",
  },
  {
    id: 1062,
    type: "single",
    category: "Neurology & Psychiatry",
    question: "Q6. You received a prescription of Selegiline 5mg bd x 30days. At what times would you counsel the patient to take the medications?",
    options: ["8am and 8pm", "6am and 6pm", "6am and 12pm", "8am and 6pm"],
    correct: "6am and 12pm",
    explanation: "Selegiline is usually taken earlier in the day to reduce insomnia risk.",
    explainCorrect: "6am and 12pm is the best option because it spaces the second dose to midday rather than bedtime.",
  },
  {
    id: 1063,
    type: "single",
    category: "Infectious Diseases",
    question: "Q7. Which of these antibiotics is ineffective for managing listeria meningitis?",
    options: ["Ceftriaxone", "Ampicillin", "Gentamicin", "Co-trimoxazole"],
    correct: "Ceftriaxone",
    explanation: "Listeria is intrinsically resistant to cephalosporins.",
    explainCorrect: "Ceftriaxone is the ineffective option here because Listeria is not reliably covered by cephalosporins.",
  },
  {
    id: 1064,
    type: "single",
    category: "Infectious Diseases",
    question: "Q8. Which of the following is not effective for managing cryptococcal meningitis?",
    options: ["Flucytosine", "Liposomal amphotericin B", "Griseofulvin", "Fluconazole"],
    correct: "Griseofulvin",
    explanation: "Griseofulvin is an antifungal used for dermatophyte infections, not cryptococcal meningitis.",
    explainCorrect: "Griseofulvin is the exception because it is not used for cryptococcal meningitis.",
  },
  {
    id: 1065,
    type: "single",
    category: "Infectious Diseases",
    question: "Q9. All these are true about corticosteroid use in meningitis except?",
    options: ["Reduces mortality in meningitis patients", "Should be administered 20 mins before antibiotics or with the first dose of the antibiotic", "Reduces hearing loss", "Increases CSF penetration of antibiotics"],
    correct: "Increases CSF penetration of antibiotics",
    explanation: "Dexamethasone can reduce inflammation and complications, but it does not increase CSF antibiotic penetration.",
    explainCorrect: "Increasing CSF penetration of antibiotics is the false statement here.",
  },
  {
    id: 1066,
    type: "single",
    category: "Infectious Diseases",
    question: "Q10. All these are diluents that can be used for artesunate reconstitution?",
    options: ["Sodium bicarbonate", "Water for injection", "Normal saline", "5% dextrose"],
    correct: "Sodium bicarbonate",
    explanation: "Artesunate for injection is classically reconstituted with sodium bicarbonate before further dilution.",
    explainCorrect: "Sodium bicarbonate is the reconstitution fluid in this item.",
  },
  {
    id: 1067,
    type: "single",
    category: "Infectious Diseases",
    question: "Q11. How long can a reconstituted artesunate be stored before administration?",
    options: ["6 hrs", "4 hrs", "1.5 hrs", "8 hrs"],
    correct: "1.5 hrs",
    explanation: "Reconstituted artesunate is unstable and should be used promptly after preparation.",
    explainCorrect: "1.5 hours is the intended answer here.",
  },
  {
    id: 1068,
    type: "single",
    category: "Infectious Diseases",
    question: "Q12. What is the rationale for giving artemisinin based combination therapies for 3 days?",
    options: ["To ensure compliance", "To cover for 1-2 asexual cycles of the plasmodium", "To prevent reinfection", "To confer natural immunity"],
    correct: "To cover for 1-2 asexual cycles of the plasmodium",
    explanation: "A 3-day ACT course covers the parasite lifecycle long enough to clear susceptible stages.",
    explainCorrect: "Covering 1 to 2 asexual cycles is the rationale behind the 3-day regimen.",
  },
  {
    id: 1069,
    type: "single",
    category: "Infectious Diseases",
    question: "Q13. Why should IM quinine be avoided at the buttocks?",
    options: ["Risk of hypoglycemia", "Risk of sciatic nerve injury", "Risk of hypotension", "Risk of cinchonism"],
    correct: "Risk of sciatic nerve injury",
    explanation: "Deep gluteal injections can injure the sciatic nerve.",
    explainCorrect: "Sciatic nerve injury is the key reason to avoid the buttock site for IM quinine.",
  },
  {
    id: 1070,
    type: "single",
    category: "Infectious Diseases",
    question: "Q14. After the first dose of IV artesunate, a patient can tolerate feeds and orals. What is the minimum time required before switching from IV artesunate to oral ACTs?",
    options: ["8 hrs", "4 hrs", "24 hrs", "3 days"],
    correct: "24 hrs",
    explanation: "Oral ACTs are usually started once the patient can tolerate oral therapy after about 24 hours.",
    explainCorrect: "24 hours is the intended minimum time in this item.",
  },
  {
    id: 1071,
    type: "single",
    category: "Infectious Diseases",
    question: "Q15. Fatty meal should be avoided when taking this antimalarial?",
    options: ["Artemether-lumefantrine", "Dihydroartemisinin-piperaquine", "Artesunate-amodiaquine", "Artesunate-pyronaridine"],
    correct: "Dihydroartemisinin-piperaquine",
    explanation: "Dihydroartemisinin-piperaquine is commonly taken away from food to limit increased exposure and adverse effects.",
    explainCorrect: "Dihydroartemisinin-piperaquine is the best answer in this list.",
  },
  {
    id: 1072,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q16. Proximal DVT refers to venous thrombosis in all the following veins except?",
    options: ["Peroneal vein", "Iliac vein", "Femoral vein", "Popliteal vein"],
    correct: "Peroneal vein",
    explanation: "Proximal DVT involves veins above the knee such as the popliteal, femoral, and iliac veins.",
    explainCorrect: "The peroneal vein is the exception because it is a distal calf vein.",
  },
  {
    id: 1073,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q17. All the following are late complications of deep vein thrombosis except?",
    options: ["Chronic thromboembolic pulmonary hypertension", "Pulmonary embolism", "Post thrombotic syndrome", "Recurrent thromboembolism"],
    correct: "Pulmonary embolism",
    explanation: "Pulmonary embolism is an acute complication, not a late sequela of DVT.",
    explainCorrect: "Pulmonary embolism is the exception because it is usually an acute complication.",
  },
  {
    id: 1074,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q18. All these drugs are oral factor Xa inhibitors except?",
    options: ["Edoxaban", "Fondaparinux", "Rivaroxaban", "Apixaban"],
    correct: "Fondaparinux",
    explanation: "Fondaparinux is a parenteral factor Xa inhibitor, not an oral agent.",
    explainCorrect: "Fondaparinux is the exception because it is not given orally.",
  },
  {
    id: 1075,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q19. Initial parenteral anticoagulation is not required for all the following factor Xa inhibitors except?",
    options: ["Rivaroxaban", "Fondaparinux", "Edoxaban", "Apixaban"],
    correct: "Edoxaban",
    explanation: "Edoxaban requires an initial parenteral anticoagulant lead-in in many treatment pathways.",
    explainCorrect: "Edoxaban is the exception because it requires initial parenteral anticoagulation.",
  },
  {
    id: 1076,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q20. The following are components of the Wells score for DVT except?",
    options: ["Swelling of the entire leg", "Active cancer", "Previous history of DVT", "Bedridden for longer than 3 days"],
    correct: "Bedridden for longer than 3 days",
    explanation: "The Wells score includes cancer, swelling, and previous DVT, while the exact immobilisation item is usually phrased differently in standard scoring tables.",
    explainCorrect: "Bedridden for longer than 3 days is the exception in this item.",
  },
  {
    id: 1077,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q21. All these are true about warfarin therapy in DVT except?",
    options: ["Reduce intake of green leafy vegetables while taking warfarin", "Warfarin is best taken at night", "Warfarin can cause osteoporosis", "Warfarin is prothrombotic"],
    correct: "Warfarin is prothrombotic",
    explanation: "Warfarin is an anticoagulant; it is not prothrombotic when used correctly.",
    explainCorrect: "Warfarin is prothrombotic is the false statement here.",
  },
  {
    id: 1078,
    type: "single",
    category: "Endocrinology",
    question: "Q22. All these are true about HbA1c except?",
    options: ["Measures the amount of glycated haemoglobin", "Useful in assessing patient's compliance", "Can be used as a monitoring parameter for all diabetics", "Serves as a retrospective marker for glycaemic control"],
    correct: "Can be used as a monitoring parameter for all diabetics",
    explanation: "HbA1c is useful in many patients, but not universally reliable in every diabetic situation.",
    explainCorrect: "That statement is the exception because HbA1c is not suitable for every diabetic patient in all contexts.",
  },
  {
    id: 1079,
    type: "single",
    category: "Hematology",
    question: "Q23. Which parameter is ideal for assessing compliance in sickle cell patients?",
    options: ["Fasting blood glucose", "Glycated haemoglobin", "Oral glucose tolerance test", "Fructosamine"],
    correct: "Fructosamine",
    explanation: "Fructosamine reflects shorter-term glycaemic control and is less affected by hemoglobin abnormalities than HbA1c.",
    explainCorrect: "Fructosamine is the best option listed for sickle cell patients.",
  },
  {
    id: 1080,
    type: "single",
    category: "Endocrinology",
    question: "Q24. All these are true about C-peptide assay in diabetes except?",
    options: ["Can help distinguish type 1 diabetes from type 2 diabetes", "Detect the levels of C-reactive protein", "Released in equimolar quantities with insulin", "Provides information on the secretory potential of the beta cells"],
    correct: "Detect the levels of C-reactive protein",
    explanation: "C-peptide is a marker of endogenous insulin secretion, not a marker of inflammation.",
    explainCorrect: "Detecting C-reactive protein is the exception because C-peptide is not used for that purpose.",
  },
  {
    id: 1081,
    type: "single",
    category: "Endocrinology",
    question: "Q25. Longterm therapy of metformin can lead to?",
    options: ["Haemolytic anaemia", "Megaloblastic anaemia", "Iron deficiency anaemia", "Sideroblastic anaemia"],
    correct: "Megaloblastic anaemia",
    explanation: "Long-term metformin use can reduce vitamin B12 absorption and lead to megaloblastic anaemia.",
    explainCorrect: "Megaloblastic anaemia is the expected long-term issue in this item.",
  },
  {
    id: 1082,
    type: "single",
    category: "Endocrinology",
    question: "Q26. Which of these sulfonylureas is preferably taken 30 mins before meals?",
    options: ["Glipizide", "Gliclazide", "Glimepiride", "Glibenclamide"],
    correct: "Glibenclamide",
    explanation: "Glibenclamide is commonly taken before meals to match its glucose-lowering effect with food intake.",
    explainCorrect: "Glibenclamide is the preferred 30-minute-before-meals choice here.",
  },
  {
    id: 1083,
    type: "single",
    category: "Endocrinology",
    question: "Q27. Which of these is the least preferred in cases of hypoglycemia in a patient who can tolerate orals?",
    options: ["Lucozade", "Coca cola", "Milk", "Sugar cubes"],
    correct: "Milk",
    explanation: "Milk is slower to correct hypoglycaemia than fast-acting carbohydrate options.",
    explainCorrect: "Milk is the least preferred option because it acts more slowly than the other choices.",
  },
  {
    id: 1084,
    type: "single",
    category: "Endocrinology",
    question: "Q28. All these are autonomic signs of hypoglycaemia except?",
    options: ["Sweating", "Tremors", "Anxiety", "Dizziness"],
    correct: "Dizziness",
    explanation: "Sweating, tremor, and anxiety are autonomic symptoms, while dizziness is more neuroglycopenic.",
    explainCorrect: "Dizziness is the exception because it is not a classic autonomic sign.",
  },
  {
    id: 1085,
    type: "single",
    category: "Infectious Diseases",
    question: "Q29. Nevirapine is not recommended for use among persons infected with HIV type 2 or those with dual HIV 1&2 infection BECAUSE it is ineffective against type 2 HIV, also most patients with HIV 2 initiated on nevirapine tend to develop hypersensitivity reactions.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[0],
    explanation: "Nevirapine is avoided in HIV-2 because it is not reliably active and can be associated with hypersensitivity.",
    explainCorrect: "Both statements are true and the reason explains why nevirapine is not recommended in HIV-2 or dual infection.",
  },
  {
    id: 1086,
    type: "single",
    category: "Infectious Diseases",
    question: "Q30. In children less than 5 years of age, absolute CD4 count should not be used to assess immunologic function for treatment initiation as in adults BECAUSE such children tend to have more CD4 cells as compared to adults so using absolute CD4 may be misleading.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[0],
    explanation: "Young children naturally have higher CD4 counts, so age-adjusted interpretation is needed.",
    explainCorrect: "Both statements are true and the reason supports the first statement.",
  },
  {
    id: 1087,
    type: "single",
    category: "Infectious Diseases",
    question: "Q31. Key populations in the context of HIV/AIDS menace do not pose any significant threat in HIV transmission BECAUSE they constitute the window of hope in the fight against HIV since they have low HIV prevalence values as compared to the general population.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[4],
    explanation: "Key populations are important drivers of transmission and do not have lower prevalence than the general population.",
    explainCorrect: "Both statements are false.",
  },
  {
    id: 1088,
    type: "single",
    category: "Infectious Diseases",
    question: "Q32. In treating a patient with co-morbid TB and HIV infections nevirapine and rifampicin co-administration will have to be avoided BECAUSE both drugs have side effects whose additive effect can result in hepatotoxicity.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[0],
    explanation: "The combination is avoided because rifampicin strongly induces metabolism and the pair can also increase toxicity concerns.",
    explainCorrect: "Both statements are accepted as true in this item and the reason explains the avoidance.",
  },
  {
    id: 1089,
    type: "single",
    category: "Infectious Diseases",
    question: "Q33. Immune inflammatory Reconstitution Syndrome (IRIS) occurs after HAART initiation BECAUSE previously quiet, dormant, sleeping or incubating diseases become symptomatic or worse after the introduction of HAART.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[0],
    explanation: "IRIS is the paradoxical worsening or unmasking of infections after immune recovery begins.",
    explainCorrect: "Both statements are true and the second explains the first.",
  },
  {
    id: 1090,
    type: "single",
    category: "Infectious Diseases",
    question: "Q34. When treating a patient on AZT/3TC/EFV who has developed IRS related herpes zoster and needs acyclovir, it is not important to monitor haemoglobin levels BECAUSE both zidovudine and acyclovir have no effect on bone marrow suppression.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[4],
    explanation: "Zidovudine can cause anemia, so haemoglobin monitoring remains important.",
    explainCorrect: "Both statements are false.",
  },
  {
    id: 1091,
    type: "single",
    category: "Infectious Diseases",
    question: "Q35. In selecting ARVs for treatment naive patients in Ghana it is recommended to use 2 nucleoside reverse transcriptase inhibitors + 1 non-nucleoside reverse transcriptase inhibitor (or + 1 protease inhibitor for HIV2) BECAUSE integrase strand transfer inhibitors and fusion inhibitors are not recommended products in Ghana's HIV treatment protocol.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[2],
    explanation: "The first statement reflects the standard regimen pattern used in this setting, while the second is not correct as a general exclusion statement.",
    explainCorrect: "The first statement is true and the second is false.",
  },
  {
    id: 1092,
    type: "single",
    category: "Infectious Diseases",
    question: "Q36. HIV-infected patients who develop NNRTI-induced hypersensitivity reaction (HSR) can subsequently be given maximum doses of the offending medicine after stabilization BECAUSE giving high doses of the offending drug after the initial reaction usually offers protection against future episodes of HSR.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[4],
    explanation: "Re-exposure to the offending NNRTI after hypersensitivity is unsafe.",
    explainCorrect: "Both statements are false.",
  },
  {
    id: 1093,
    type: "single",
    category: "Infectious Diseases",
    question: "Q37. Interpretation of positive HIV antibody test results in children aged less than 18 months should be done carefully BECAUSE younger children can test positive to maternal antibody in their system which clears completely with age after 18 months.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[0],
    explanation: "Maternal antibodies can persist in infants and confound serologic HIV testing.",
    explainCorrect: "Both statements are true and the reason explains the first.",
  },
  {
    id: 1094,
    type: "single",
    category: "Infectious Diseases",
    question: "Q38. Tuberculosis of the spine can be described as pulmonary TB BECAUSE extra-pulmonary TB affects body parts other than the lungs.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[3],
    explanation: "Spinal TB is extrapulmonary TB, not pulmonary TB.",
    explainCorrect: "The first statement is false and the second statement is true.",
  },
  {
    id: 1095,
    type: "single",
    category: "Infectious Diseases",
    question: "Q39. HIV is a sexually transmitted infection BECAUSE HIV can be transmitted by vertical transmission.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[1],
    explanation: "HIV is sexually transmitted and can also be transmitted vertically, but vertical transmission is not the explanation for the sexual transmission statement.",
    explainCorrect: "Both statements are true but the second is not a correct explanation of the first.",
  },
  {
    id: 1096,
    type: "single",
    category: "Infectious Diseases",
    question: "Q40. A switch to second line is recommended when there is virological failure BECAUSE virological failure is recognised as a persistent viral load below 1000 RNA copies/ml after at least 6 months on antiretroviral therapy.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[2],
    explanation: "Virological failure is typically defined by a persistently elevated viral load, not a value below 1000 copies/ml.",
    explainCorrect: "The first statement is true and the second is false.",
  },
  {
    id: 1097,
    type: "single",
    category: "Infectious Diseases",
    question: "Q41. All HIV exposed infants irrespective of feeding options are to be provided with Zidovudine within 48 hours. Where Zidovudine is contraindicated Nevirapine can be used in these infants.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[1],
    explanation: "The prophylaxis principle is correct, but the reason given is not the explanatory basis.",
    explainCorrect: "Both statements are true but the second does not explain the first.",
  },
  {
    id: 1098,
    type: "single",
    category: "Infectious Diseases",
    question: "Q42. HIV infection is currently not curable in Ghana. However effective retroviral therapy is available country-wide at accredited centres at regional and district levels.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[1],
    explanation: "HIV is not curable, and ART access is widely available through accredited centres.",
    explainCorrect: "Both statements are true but the second is not the direct explanation of the first.",
  },
  {
    id: 1099,
    type: "single",
    category: "Infectious Diseases",
    question: "Q43. Zidovudine is a Protease Inhibitor. It is contraindicated in liver dysfunction.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[4],
    explanation: "Zidovudine is a nucleoside reverse transcriptase inhibitor, not a protease inhibitor.",
    explainCorrect: "Both statements are false.",
  },
  {
    id: 1100,
    type: "single",
    category: "Infectious Diseases",
    question: "Q44. The physician in consultation with the other team members and the client may change antiretroviral therapy when there is drug toxicity and treatment failure because treatment failure is defined by disease progression, immunologically by an increase in CD4 count or virologically by an increase in viral load.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[2],
    explanation: "Therapy can be changed for toxicity or treatment failure, but treatment failure is not defined by an increase in CD4 count.",
    explainCorrect: "The first statement is true and the second is false.",
  },
  {
    id: 1101,
    type: "single",
    category: "Neurology & Psychiatry",
    question: "Q45. High protein diet should be avoided while taking levodopa BECAUSE amino acids compete with levodopa for gastrointestinal absorption.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[0],
    explanation: "Protein can reduce levodopa absorption and clinical effect.",
    explainCorrect: "Both statements are true and the second explains the first.",
  },
  {
    id: 1102,
    type: "single",
    category: "Hematology",
    question: "Q46. Pethidine should be avoided in sickle cell disease patients BECAUSE pethidine can cause opioid induced constipation.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[1],
    explanation: "Pethidine is generally avoided in sickle cell disease for safety reasons, but constipation alone is not the main explanation.",
    explainCorrect: "Both statements are true but the second is not the main explanation for avoiding pethidine in sickle cell disease.",
  },
  {
    id: 1103,
    type: "single",
    category: "Hematology",
    question: "Q47. Pethidine is very addictive BECAUSE pethidine can cause miosis.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[2],
    explanation: "Pethidine is addictive, but miosis is not the reason for its addictive potential.",
    explainCorrect: "The first statement is true and the second is false.",
  },
  {
    id: 1104,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q48. Azithromycin can be an add on therapy in asthma management BECAUSE azithromycin has a better gram positive coverage than erythromycin.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[2],
    explanation: "Azithromycin may be used as an add-on in some asthma patients, but gram-positive coverage is not the reason.",
    explainCorrect: "The first statement is true and the second is false.",
  },
  {
    id: 1105,
    type: "single",
    category: "Endocrinology",
    question: "Q49. Orlistat can be used in weight management in obese patients BECAUSE Orlistat is an analogue of the satiety hormone, amylin.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[2],
    explanation: "Orlistat is a lipase inhibitor used for weight management, but it is not an amylin analogue.",
    explainCorrect: "The first statement is true and the second is false.",
  },
  {
    id: 1106,
    type: "single",
    category: "Hematology",
    question: "Q50. Penicillin V is used as prophylaxis for infections in all sickle cell patients BECAUSE it has activity against encapsulated organisms.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[3],
    explanation: "Penicillin V is used in selected sickle cell patients, especially children, because it covers encapsulated organisms.",
    explainCorrect: "The first statement is false and the second is true.",
  },
  {
    id: 1107,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q51. Amiodarone can cause both hypothyroidism and hyperthyroidism BECAUSE amiodarone can inhibit deiodinase enzyme.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[0],
    explanation: "Amiodarone has major thyroid effects because of its iodine content and deiodinase inhibition.",
    explainCorrect: "Both statements are true and the reason explains the first.",
  },
];
