export const seventhBatchQuestions = [
  {
    id: 1159,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q1. XM, a 76-year-old male patient, is admitted with heart failure secondary to diabetes mellitus. He presents with vomiting, diaphoresis, and severe chest pain. The onset of pain was sudden, persistently increasing in intensity, and not relieved by aceclofenac. These clinical features are consistent with which one of the following conditions?",
    options: ["Unstable angina pectoris", "Myocardial infarction", "Decubitus angina", "Cardiomyopathy"],
    correct: "Myocardial infarction",
    explanation: "Sudden severe chest pain with diaphoresis and vomiting is highly suggestive of myocardial infarction.",
    explainCorrect: "Myocardial infarction is the best fit for this presentation.",
  },
  {
    id: 1160,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q2. Which one of the following factors best explains why sublingual glyceryl trinitrate (GTN) spray is preferred over the oral route in the management of angina?",
    options: ["High bioavailability", "Quick onset of action", "To prevent enterohepatic recycling", "To minimize headache"],
    correct: "Quick onset of action",
    explanation: "Sublingual GTN bypasses first-pass metabolism and works quickly for acute angina relief.",
    explainCorrect: "Quick onset of action is the key advantage of the sublingual route.",
  },
  {
    id: 1161,
    type: "single",
    category: "Endocrinology",
    question: "Q3. Hyperkalemia in diabetic ketoacidosis is mainly due to:",
    options: ["Compromised renal function secondary to hypovolemia", "Extracellular shift due to acidosis", "Extracellular shift due to alkalosis", "Dehydration and subsequent hemoconcentration"],
    correct: "Extracellular shift due to acidosis",
    explanation: "Acidosis and insulin deficiency shift potassium out of cells, raising serum potassium.",
    explainCorrect: "Extracellular shift due to acidosis is the main mechanism in DKA.",
  },
  {
    id: 1162,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q4. According to the NYHA Functional Classification, which of the following describes a patient with cardiac disease who is comfortable at rest, but ordinary physical activity causes fatigue, palpitations, and dyspnea?",
    options: ["NYHA IV", "NYHA III", "NYHA II", "NYHA I"],
    correct: "NYHA II",
    explanation: "NYHA II means slight limitation of activity with symptoms on ordinary exertion but comfort at rest.",
    explainCorrect: "NYHA II is the correct functional class.",
  },
  {
    id: 1163,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q5. A 58-year-old male reports that he recently stopped taking his blood pressure medications because of swelling in his feet that began shortly after he started treatment. Which of the following is most likely to cause peripheral edema?",
    options: ["Atenolol", "Clonidine", "Hydralazine", "Felodipine"],
    correct: "Felodipine",
    explanation: "Dihydropyridine calcium channel blockers commonly cause peripheral edema.",
    explainCorrect: "Felodipine is the most likely cause of peripheral oedema.",
  },
  {
    id: 1164,
    type: "single",
    category: "Endocrinology",
    question: "Q6. Which of the following is not a risk factor for goitre?",
    options: ["Male gender", "Age above 40", "Exposure to radiation", "Lack of dietary iodine"],
    correct: "Male gender",
    explanation: "Goitre is more commonly associated with female sex, iodine deficiency, and radiation exposure.",
    explainCorrect: "Male gender is the exception here.",
  },
  {
    id: 1165,
    type: "single",
    category: "Infectious Diseases",
    question: "Q7. Which of the following will be the most suitable antibiotic prescribed for an elderly woman with renal insufficiency?",
    options: ["Gatifloxacin", "Norfloxacin", "Ofloxacin", "Moxifloxacin"],
    correct: "Moxifloxacin",
    explanation: "Moxifloxacin is less dependent on renal elimination than the other options.",
    explainCorrect: "Moxifloxacin is the best choice in renal insufficiency among the listed options.",
  },
  {
    id: 1166,
    type: "single",
    category: "Endocrinology",
    question: "Q8. Below are the OGTT results of a 55-year-old obese man who was referred to the clinic: Fasting Blood Glucose 7.9 mmol/L and 2-hour Post-Prandial 12.5 mmol/L. Which of the following statements about his management is/are correct?",
    options: [
      "A. Recommended first-line therapy is sulphonylurea",
      "B. Patient has pre-diabetes",
      "C. Glycemic control should be monitored with HbA1c once every month",
      "D. GLP-1 analogue will stimulate insulin production and cause weight loss",
    ],
    correct: "D. GLP-1 analogue will stimulate insulin production and cause weight loss",
    explanation: "The OGTT values are consistent with diabetes, and GLP-1 analogues can increase insulin secretion and support weight loss.",
    explainCorrect: "Option D is correct.",
  },
  {
    id: 1167,
    type: "single",
    category: "Endocrinology",
    caseId: "mr-mh-diabetes-ckd-heart-failure",
    caseBlock: "Mr. MH is a 50-year-old man with type 2 diabetes, left ventricular systolic dysfunction, and chronic kidney disease with eGFR 28 mL/min/1.73m2. Use this case for the related treatment question.",
    question: "Q9. Mr. MH is a 50-year-old Type II diabetic patient with left ventricular systolic dysfunction. He has developed chronic kidney disease. His eGFR is 28 mL/min/1.73m2 and his HbA1c is 7.0%. His current medications include metformin, lisinopril, carvedilol, and furosemide. His diabetes should be managed appropriately as follows:",
    options: ["Change Metformin to gliclazide", "Change Metformin to a thiazolidinedione", "Maintain Metformin", "Change Metformin to short-acting insulin"],
    correct: "Change Metformin to short-acting insulin",
    explanation: "Metformin is usually stopped or replaced in advanced CKD because of lactic acidosis risk.",
    explainCorrect: "Short-acting insulin is the safest option among the choices given.",
  },
  {
    id: 1168,
    type: "single",
    category: "Infectious Diseases",
    question: "Q10. Open, fresh, surgical wounds involving major breaks in sterile technique or gross spillage from the GI tract, or incisions in which acute, non-purulent inflammation occurs, are referred to as:",
    options: ["Clean wounds", "Unclean wounds", "Contaminated wounds", "Clean-contaminated wounds"],
    correct: "Contaminated wounds",
    explanation: "Gross spillage and major breaks in sterile technique classify a wound as contaminated.",
    explainCorrect: "Contaminated wounds is the correct classification.",
  },
  {
    id: 1169,
    type: "single",
    category: "Infectious Diseases",
    question: "Q11. Which of these antibiotics is not a third-generation cephalosporin?",
    options: ["Cefotaxime", "Cefepime", "Ceftazidime", "Cefixime"],
    correct: "Cefepime",
    explanation: "Cefepime is a fourth-generation cephalosporin.",
    explainCorrect: "Cefepime is the exception because it is fourth generation, not third generation.",
  },
  {
    id: 1170,
    type: "single",
    category: "Respiratory Disorders",
    question: "Q12. According to GINA 2025 guidelines, which of the following inhaler medications is recommended for Maintenance and Reliever Therapy (MART) regimen?",
    options: ["Formoterol & Budesonide", "Salbutamol & Salmeterol", "Salmeterol & Fluticasone", "Budesonide only"],
    correct: "Formoterol & Budesonide",
    explanation: "MART uses an inhaled corticosteroid combined with formoterol.",
    explainCorrect: "Formoterol and budesonide is the correct MART combination.",
  },
  {
    id: 1171,
    type: "single",
    category: "Infectious Diseases",
    question: "Q13. Which of these antibiotics is effective against ESBL (Extended Spectrum Beta-Lactamase) resistant organisms?",
    options: ["Piperacillin with tazobactam", "Vancomycin", "Ceftazidime", "Meropenem"],
    correct: "Meropenem",
    explanation: "Carbapenems such as meropenem are reliable options for many ESBL-producing organisms.",
    explainCorrect: "Meropenem is the best answer in this list.",
  },
  {
    id: 1172,
    type: "single",
    category: "Women's & Men's Health",
    question: "Q14. Gonadotropin-releasing hormone (GnRH) agonists are used in premenopausal women undergoing fibroid treatment prior to surgery. Which of these is NOT an indication for the use of GnRH in such women?",
    options: ["To reduce blood loss", "To reduce the size of fibroid", "To reduce the risk of blood transfusion", "To prevent loss of libido"],
    correct: "To prevent loss of libido",
    explanation: "GnRH agonists are used to shrink fibroids and reduce operative blood loss, not to prevent libido loss.",
    explainCorrect: "Preventing loss of libido is the exception.",
  },
  {
    id: 1173,
    type: "single",
    category: "Rheumatology & Pain",
    question: "Q15. In acute pain management, fentanyl is preferred to morphine because:",
    options: ["It is 100× more effective", "It has a shorter onset of action", "It has less risk of respiratory depression", "It has less risk of nausea and vomiting"],
    correct: "It has a shorter onset of action",
    explanation: "Fentanyl is highly lipophilic and has a rapid onset of action.",
    explainCorrect: "Shorter onset of action is the best choice.",
  },
  {
    id: 1174,
    type: "single",
    category: "Gastrointestinal Disorders",
    question: "Q16. Which of the following is NOT consistent with a diagnosis of acute pancreatitis?",
    options: ["Abdominal pain that radiates to the back", "Hypoglycemia", "Serum amylase and/or lipase greater than 3× the upper limit of normal", "Characteristic findings from abdominal imaging"],
    correct: "Hypoglycemia",
    explanation: "Acute pancreatitis is associated with abdominal pain and elevated pancreatic enzymes, not hypoglycemia as a defining feature.",
    explainCorrect: "Hypoglycemia is the exception here.",
  },
  {
    id: 1175,
    type: "single",
    category: "Hematology",
    question: "Q17. Penicillin prophylaxis against pneumonia in persons with sickle cell disease is most useful at ages:",
    options: ["Above 60 years", "Above 70 years", "2 months – 5 years", "12 – 18 years"],
    correct: "2 months – 5 years",
    explanation: "Children with sickle cell disease are most vulnerable early in life and benefit from penicillin prophylaxis.",
    explainCorrect: "2 months to 5 years is the correct age range.",
  },
  {
    id: 1176,
    type: "single",
    category: "Oncology",
    question: "Q18. Which of these medications is most likely to cause hand-foot syndrome (palmar-plantar erythrodysesthesia)?",
    options: ["Ibuprofen", "Lisinopril", "Omeprazole", "Capecitabine"],
    correct: "Capecitabine",
    explanation: "Capecitabine is well known for causing hand-foot syndrome.",
    explainCorrect: "Capecitabine is the correct answer.",
  },
  {
    id: 1177,
    type: "single",
    category: "Renal & Electrolyte Disorders",
    question: "Q19. Which of these options is most suitable as first-line management of hyperkalemia in a patient with impaired renal function?",
    options: ["IV furosemide", "IV salbutamol", "10 units soluble insulin plus 25–50% dextrose", "Calcium gluconate 10%"],
    correct: "10 units soluble insulin plus 25–50% dextrose",
    explanation: "Insulin with dextrose shifts potassium into cells and is a standard initial treatment to lower serum potassium.",
    explainCorrect: "Insulin plus dextrose is the best answer here.",
  },
  {
    id: 1178,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q20. All these medications can be used in a person with Type 2 diabetes mellitus, peripheral artery disease, and heart failure EXCEPT:",
    options: ["Cilostazol", "Atorvastatin", "Gliclazide", "Low-dose aspirin"],
    correct: "Cilostazol",
    explanation: "Cilostazol is contraindicated in heart failure.",
    explainCorrect: "Cilostazol is the exception.",
  },
  {
    id: 1179,
    type: "single",
    category: "Pharmacy Practice",
    question: "Q21. All these agents/interventions are indicated for angle-closure glaucoma EXCEPT:",
    options: ["Timolol", "Brinzolamide", "Pilocarpine", "Tropicamide"],
    correct: "Tropicamide",
    explanation: "Tropicamide is a mydriatic and can worsen angle closure, not treat it.",
    explainCorrect: "Tropicamide is the exception.",
  },
  {
    id: 1180,
    type: "single",
    category: "Women's & Men's Health",
    question: "Q22. Breast self-examination should be taught as a means of creating breast cancer awareness and encouraging early detection of breast diseases. Which of the following statements is correct?",
    options: [
      "Should be done a week after the menstrual period in premenopausal women, and on a particular day of each month for postmenopausal women.",
      "Should be done two weeks before the menstrual period in premenopausal women, and on a particular day of each month for postmenopausal women.",
      "Should be done one week before the menstrual period in premenopausal women, and on a particular day of each month for postmenopausal women.",
      "Should be done three days after the menstrual period in premenopausal women, and on a particular day of each month for postmenopausal women.",
    ],
    correct: "Should be done a week after the menstrual period in premenopausal women, and on a particular day of each month for postmenopausal women.",
    explanation: "BSE is best done after menses when the breasts are least tender and swollen.",
    explainCorrect: "The first option is correct.",
  },
  {
    id: 1181,
    type: "single",
    category: "Hematology",
    question: "Q23. Indicate the food source with the highest iron content per 100 g:",
    options: ["Plantain", "Banana", "Natural cocoa powder (unsweetened)", "Millet"],
    correct: "Natural cocoa powder (unsweetened)",
    explanation: "Unsweetened cocoa powder is a notably iron-rich food compared with the other listed items.",
    explainCorrect: "Natural cocoa powder has the highest iron content here.",
  },
  {
    id: 1182,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q24. In a patient receiving digoxin for congestive heart failure, conditions that may facilitate the appearance of toxicity include:",
    options: ["Hypocalcemia", "Hypomagnesemia", "Hyperkalemia", "Hypernatremia"],
    correct: "Hypomagnesemia",
    explanation: "Low magnesium increases susceptibility to digoxin toxicity.",
    explainCorrect: "Hypomagnesemia is the best answer.",
  },
  {
    id: 1183,
    type: "single",
    category: "Endocrinology",
    question: "Q25. Which hormone is released from the hypothalamus in the Hypothalamus-Pituitary-Adrenal (HPA) axis?",
    options: ["TRH", "ACTH", "TSH", "CRH"],
    correct: "CRH",
    explanation: "Corticotropin-releasing hormone from the hypothalamus stimulates ACTH release from the pituitary.",
    explainCorrect: "CRH is the correct hypothalamic hormone in the HPA axis.",
  },
  {
    id: 1184,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q26. Peripheral arterial occlusive disease is associated with an increased risk of cardiovascular events. This risk is reduced by all these measures EXCEPT:",
    options: ["Smoking cessation", "Effective blood pressure control", "Sedentary lifestyle", "Taking aspirin 75 mg orally daily"],
    correct: "Sedentary lifestyle",
    explanation: "Regular activity and risk factor reduction help lower cardiovascular risk; sedentary lifestyle does the opposite.",
    explainCorrect: "Sedentary lifestyle is the exception.",
  },
  {
    id: 1185,
    type: "single",
    category: "Pharmacy Practice",
    question: "Q27. Paracetamol overdose or poisoning may be treated using:",
    options: ["Methionine", "Desferrioxamine mesylate", "Naloxone hydrochloride", "Dicobalt edetate"],
    correct: "Methionine",
    explanation: "Methionine is a recognised antidotal option for paracetamol poisoning in some settings.",
    explainCorrect: "Methionine is the correct answer.",
  },
  {
    id: 1186,
    type: "single",
    category: "Endocrinology",
    question: "Q28. Which one of the following statements is FALSE about Liraglutide?",
    options: ["Treatment with Liraglutide is associated with weight loss", "It is contraindicated in inflammatory bowel disease", "It should be given via subcutaneous injection", "It blocks GLP-1 receptors to reduce insulin secretion"],
    correct: "It blocks GLP-1 receptors to reduce insulin secretion",
    explanation: "Liraglutide is a GLP-1 receptor agonist, not an antagonist.",
    explainCorrect: "The false statement is that it blocks GLP-1 receptors.",
  },
  {
    id: 1187,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q29. Regarding the use of Spironolactone in heart failure:",
    options: ["It reduces mortality in heart failure", "The maximum dose of Spironolactone in heart failure is 50 mg", "Its introduction in heart failure is from stages 2 to 4", "It is used in heart failure because of its weak diuretic effect"],
    correct: "It reduces mortality in heart failure",
    explanation: "Spironolactone is valued in heart failure primarily because it improves survival.",
    explainCorrect: "The most correct and important statement is that it reduces mortality in heart failure.",
  },
  {
    id: 1188,
    type: "single",
    category: "Neurology & Psychiatry",
    question: "Q30. All the following drugs effectively treat absence (petit mal) seizures EXCEPT:",
    options: ["Clonazepam", "Ethosuximide", "Phenytoin", "Valproic acid"],
    correct: "Phenytoin",
    explanation: "Phenytoin is not effective for absence seizures and may worsen them.",
    explainCorrect: "Phenytoin is the exception.",
  },
  {
    id: 1189,
    type: "single",
    category: "Hematology",
    question: "Q31. Important types of anemia and their causes include all the following EXCEPT:",
    options: ["Microcytic hypochromic anemia: severe hookworm infection", "Megaloblastic anemia: gastrectomy", "Microcytic hypochromic anemia: folic acid deficiency", "Microcytic hypochromic anemia: pregnancy"],
    correct: "Microcytic hypochromic anemia: folic acid deficiency",
    explanation: "Folate deficiency causes megaloblastic anemia rather than microcytic hypochromic anemia.",
    explainCorrect: "That pairing is the exception.",
  },
  {
    id: 1190,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q32. Increased levels of which one of the following may be associated with a decreased risk of atherosclerosis?",
    options: ["Low-density lipoproteins (LDL)", "High-density lipoproteins (HDL)", "Cholesterol", "Very-low-density lipoproteins (VLDL)"],
    correct: "High-density lipoproteins (HDL)",
    explanation: "HDL is considered protective against atherosclerosis.",
    explainCorrect: "HDL is the protective lipoprotein in this question.",
  },
  {
    id: 1191,
    type: "single",
    category: "Renal & Electrolyte Disorders",
    question: "Q33. Pre-renal acute kidney injury may be caused by all these conditions EXCEPT:",
    options: ["Sepsis", "Excessive sweating", "Burns", "Rhabdomyolysis"],
    correct: "Rhabdomyolysis",
    explanation: "Rhabdomyolysis causes intrinsic renal injury rather than pre-renal AKI.",
    explainCorrect: "Rhabdomyolysis is the exception.",
  },
  {
    id: 1192,
    type: "single",
    category: "Gastrointestinal Disorders",
    question: "Q34. Which of these medications is commonly prescribed for chronic constipation?",
    options: ["Metoclopramide", "Polyethylene glycol (PEG)", "Antispasmodics", "Antacids"],
    correct: "Polyethylene glycol (PEG)",
    explanation: "PEG is a common osmotic laxative used for chronic constipation.",
    explainCorrect: "PEG is the correct answer.",
  },
  {
    id: 1193,
    type: "single",
    category: "Gastrointestinal Disorders",
    question: "Q35. In which situation should stimulant laxatives be avoided in the treatment of constipation?",
    options: ["When immediate relief is needed", "In cases of chronic constipation", "In patients with abdominal pain of unknown origin", "For patients with occasional constipation"],
    correct: "In patients with abdominal pain of unknown origin",
    explanation: "Stimulant laxatives should be avoided when the cause of abdominal pain has not been clarified.",
    explainCorrect: "Abdominal pain of unknown origin is the key avoidance scenario.",
  },
  {
    id: 1194,
    type: "single",
    category: "Infectious Diseases",
    question: "Q36. The causative agent of syphilis is:",
    options: ["Neisseria gonorrhoeae", "Treponema pallidum", "Chlamydia trachomatis", "Herpes simplex virus"],
    correct: "Treponema pallidum",
    explanation: "Syphilis is caused by the spirochete Treponema pallidum.",
    explainCorrect: "Treponema pallidum is correct.",
  },
  {
    id: 1195,
    type: "single",
    category: "Infectious Diseases",
    question: "Q37. Which of the following STDs is caused by a virus?",
    options: ["Gonorrhea", "Chlamydia", "Human papillomavirus (HPV)", "Trichomoniasis"],
    correct: "Human papillomavirus (HPV)",
    explanation: "HPV is a viral sexually transmitted infection.",
    explainCorrect: "HPV is the correct viral STD.",
  },
  {
    id: 1196,
    type: "single",
    category: "Infectious Diseases",
    question: "Q38. A painless ulcer, known as a chancre, is characteristic of which STD?",
    options: ["Gonorrhea", "Chlamydia", "Syphilis", "HIV"],
    correct: "Syphilis",
    explanation: "A chancre is the classic primary lesion of syphilis.",
    explainCorrect: "Syphilis is the correct answer.",
  },
  {
    id: 1197,
    type: "single",
    category: "Infectious Diseases",
    question: "Q39. Which pathogen is associated with the condition known as genital warts?",
    options: ["Herpes simplex virus", "Treponema pallidum", "Human papillomavirus (HPV)", "Chlamydia trachomatis"],
    correct: "Human papillomavirus (HPV)",
    explanation: "Genital warts are caused by HPV, especially types 6 and 11.",
    explainCorrect: "HPV is the correct pathogen.",
  },
  {
    id: 1198,
    type: "single",
    category: "Infectious Diseases",
    question: "Q40. Which of the following bacteria most commonly causes impetigo?",
    options: ["Streptococcus pneumoniae", "Staphylococcus aureus", "Pseudomonas aeruginosa", "Escherichia coli"],
    correct: "Staphylococcus aureus",
    explanation: "Impetigo is most commonly caused by Staphylococcus aureus.",
    explainCorrect: "Staphylococcus aureus is the best answer.",
  },
  {
    id: 1199,
    type: "single",
    category: "Infectious Diseases",
    question: "Q41. Cellulitis is best described as:",
    options: ["Viral infection of the skin", "Allergic skin reaction", "Bacterial infection of the deeper layers of the skin", "Chronic fungal infection limited to the surface"],
    correct: "Bacterial infection of the deeper layers of the skin",
    explanation: "Cellulitis is a bacterial infection involving the deeper dermis and subcutaneous tissues.",
    explainCorrect: "Bacterial infection of the deeper layers of the skin is correct.",
  },
  {
    id: 1200,
    type: "single",
    category: "Infectious Diseases",
    question: "Q42. Which STI is most likely to cause painful sores or blisters on the genital area?",
    options: ["Gonorrhea", "Syphilis", "Genital herpes", "Trichomoniasis"],
    correct: "Genital herpes",
    explanation: "Genital herpes commonly causes painful vesicles and ulcers.",
    explainCorrect: "Genital herpes is the correct answer.",
  },
  {
    id: 1201,
    type: "single",
    category: "Infectious Diseases",
    question: "Q43. Which STI can be characterized by a frothy, yellow-green vaginal discharge with a strong odor?",
    options: ["Human papillomavirus (HPV)", "Trichomoniasis", "HIV/AIDS", "Hepatitis B"],
    correct: "Trichomoniasis",
    explanation: "Trichomoniasis classically causes a frothy, malodorous discharge.",
    explainCorrect: "Trichomoniasis is the correct answer.",
  },
  {
    id: 1202,
    type: "combo",
    category: "Infectious Diseases",
    question: "Q44. These are common clinical signs that may be noted in meningitis that occurs in both adults and children above 5 years of age:",
    statements: ["Neck stiffness", "Fever", "Bulging fontanelle"],
    correct: "B",
    explanation: "Neck stiffness and fever are common; bulging fontanelle is mainly an infant sign.",
    explainCorrect: "Option B is correct because only statements 1 and 2 fit older children and adults.",
  },
  {
    id: 1204,
    type: "single",
    category: "Gastrointestinal Disorders",
    question: "Q46. In relation to their safety profile, which of the proton pump inhibitors would be preferred in pregnancy?",
    options: ["Lansoprazole", "Omeprazole", "Pantoprazole", "None of the above"],
    correct: "Pantoprazole",
    explanation: "Pantoprazole is commonly considered a preferred PPI in pregnancy due to a reassuring safety profile.",
    explainCorrect: "Pantoprazole is the preferred option here.",
  },
  {
    id: 1205,
    type: "combo",
    category: "Renal & Electrolyte Disorders",
    question: "Q47. Which of the following medication(s) would not be appropriate for managing microproteinuria in a hypertensive patient with diabetes?",
    statements: ["Lisinopril", "Propranolol", "Hydrochlorothiazide"],
    correct: "C",
    explanation: "ACE inhibitors like lisinopril are appropriate, while propranolol and hydrochlorothiazide are not preferred for microproteinuria reduction.",
    explainCorrect: "Option C is correct because only statements 2 and 3 are not appropriate here.",
  },
  {
    id: 1206,
    type: "combo",
    category: "Gastrointestinal Disorders",
    question: "Q48. Which of these drug(s) could be used in the management of encephalopathy in liver cirrhosis?",
    statements: ["Lactulose", "Rifaximin", "Metronidazole"],
    correct: "A",
    explanation: "Lactulose and rifaximin are standard, and metronidazole may also be used in some settings.",
    explainCorrect: "Option A is correct because all three statements are acceptable in this item.",
  },
  {
    id: 1207,
    type: "single",
    category: "Endocrinology",
    question: "Q49. Identify from the group of drugs the pair of anti-thyroid drugs in use:",
    options: ["Carbamazepine and propranolol", "Propylthiouracil and atenolol", "Carbimazole and propylthiouracil", "Carbimazole and propantheline"],
    correct: "Carbimazole and propylthiouracil",
    explanation: "Carbimazole and propylthiouracil are both antithyroid drugs.",
    explainCorrect: "Carbimazole and propylthiouracil is the correct pair.",
  },
  {
    id: 1208,
    type: "single",
    category: "Rheumatology & Pain",
    question: "Q50. Opioids will manage pain at:",
    options: ["The peripheral nociceptor level (transduction)", "The dorsal horn within the spinal cord (transmission)", "The brain level (perception)", "All the levels above"],
    correct: "All the levels above",
    explanation: "Opioids can modulate pain processing at peripheral, spinal, and central levels.",
    explainCorrect: "All the levels above is the correct answer.",
  },
];
