const assertionReasonOptions = [
  "First Statement is True, Second Statement is True and is a correct explanation of the first",
  "First Statement is True, Second Statement is True but not a correct explanation of the first",
  "First Statement is True, Second Statement is False",
  "First Statement is False, second Statement is True",
  "Both Statements are False",
];

export const ninthBatchQuestions = [
  {
    id: 1259,
    type: "single",
    category: "Ophthalmology",
    question: "Q1. Which of these medications should be avoided in a person with angle-closure glaucoma?",
    options: ["Hyoscine butyl bromide", "Paracetamol", "Diclofenac", "Artificial tears"],
    correct: "Hyoscine butyl bromide",
    explanation: "Anticholinergic drugs such as hyoscine can precipitate angle-closure glaucoma.",
    explainCorrect: "Hyoscine butyl bromide is the correct answer.",
  },
  {
    id: 1260,
    type: "single",
    category: "Pharmacy Practice",
    question: "Q2. A fixed dose combination of diclofenac and chlorzoxazone requires an intervention from the pharmacist for:",
    options: ["renal function test", "liver function test", "gastric protection", "ECG investigation"],
    correct: "liver function test",
    explanation: "Chlorzoxazone can be hepatotoxic, so liver function monitoring is the key intervention.",
    explainCorrect: "Liver function test is the correct answer.",
  },
  {
    id: 1261,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q3. Cilostazol is the preferred antiplatelet in the management of peripheral artery disease because of its",
    options: ["cholesterol-lowering effect", "blood-pressure lowering effect", "vasodilating effect", "weight-reducing effect"],
    correct: "vasodilating effect",
    explanation: "Cilostazol inhibits phosphodiesterase III and improves walking distance partly through vasodilation.",
    explainCorrect: "Vasodilating effect is the best answer.",
  },
  {
    id: 1262,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q4. Which of the following Calcium Channel Blockers is the safest in patient with heart failure with reduced ejection fraction (HFrEF)?",
    options: ["Felodipine", "Verapamil", "Nifedipine", "Diltiazem"],
    correct: "Felodipine",
    explanation: "Non-dihydropyridines such as verapamil and diltiazem are avoided in HFrEF; felodipine is the safer option here.",
    explainCorrect: "Felodipine is the safest choice among the options.",
  },
  {
    id: 1263,
    type: "single",
    category: "Renal Disorders",
    question: "Q5. Accumulation of Aluminium ions observed in the brain of a renally impaired patient on haemodialysis may lead to a condition called",
    options: ["Pure red cell aplasia", "Dialysis dementia", "Osteodystrophy", "Pruritis"],
    correct: "Dialysis dementia",
    explanation: "Aluminium toxicity in dialysis patients can cause dialysis dementia.",
    explainCorrect: "Dialysis dementia is correct.",
  },
  {
    id: 1264,
    type: "single",
    category: "Renal Disorders",
    question: "Q6. The effect of Metabolic Acidosis in renally impaired patient may lead to ....",
    options: ["Hypokalaemia", "Hyperkalaemia", "Hypomagnesemia", "Anuria"],
    correct: "Hyperkalaemia",
    explanation: "Acidosis shifts potassium out of cells and can raise serum potassium.",
    explainCorrect: "Hyperkalaemia is the correct answer.",
  },
  {
    id: 1265,
    type: "single",
    category: "Neurology & Psychiatry",
    question: "Q7. Which of these medications will help with Motor Recovery in stroke patients?",
    options: ["Piracetam", "Fluoxetine", "Acetazolamide", "Clopidogrel"],
    correct: "Fluoxetine",
    explanation: "Fluoxetine has been studied for post-stroke motor recovery and rehabilitation support.",
    explainCorrect: "Fluoxetine is the intended answer.",
  },
  {
    id: 1266,
    type: "single",
    category: "Pharmacy Practice",
    question: "Q8. All these medications could cause isolated elevations of Gamma-Glutamyl Transferase (GGT) EXCEPT",
    options: ["Sodium valproate", "Carbamazepine", "Rifampicin", "Phenytoin"],
    correct: "Sodium valproate",
    explanation: "Carbamazepine, rifampicin, and phenytoin can induce enzymes and raise GGT; sodium valproate is the exception here.",
    explainCorrect: "Sodium valproate is the correct exception.",
  },
  {
    id: 1267,
    type: "single",
    category: "Endocrinology",
    question: "Q9. Which one of these products is the LEAST preferred in case of Hypoglycaemia",
    options: ["Lucozade", "Coca cola", "Milk", "Sugar Cakes"],
    correct: "Milk",
    explanation: "Milk is slower to correct hypoglycaemia because of its protein and fat content.",
    explainCorrect: "Milk is the least preferred option.",
  },
  {
    id: 1268,
    type: "single",
    category: "Infectious Diseases",
    question: "Q10. All these statements are true about Corticosteroid use in Meningitis EXCEPT",
    options: ["Reduces mortality in meningitis patients", "Should be administered 20 mins before antibiotics or with the first dose of the antibiotic", "Reduces hearing loss", "Increases CSF penetration of antibiotics"],
    correct: "Increases CSF penetration of antibiotics",
    explanation: "Corticosteroids reduce inflammation; they do not increase CSF penetration of antibiotics.",
    explainCorrect: "The false statement is that steroids increase CSF penetration of antibiotics.",
  },
  {
    id: 1269,
    type: "single",
    category: "Endocrinology",
    question: "Q11. A 30-year-old patient with type 1 diabetes mellitus with protein in her urine was noticed during rounds. Which of the following recommendations will be VALID?",
    options: ["Recommend addition of ACE inhibitor", "Add Pioglitazone to her therapy", "Add metformin to her therapy", "Beta blocker should be added to her therapy"],
    correct: "Recommend addition of ACE inhibitor",
    explanation: "ACE inhibitors reduce intraglomerular pressure and are recommended in diabetic proteinuria when appropriate.",
    explainCorrect: "ACE inhibitor is the valid recommendation.",
  },
  {
    id: 1270,
    type: "single",
    category: "Neurology & Psychiatry",
    question: "Q12. A clinical syndrome of rapid onset of focal deficits of the brain function which resolves within 24 hours regardless of whether there is imaging evidence of new permanent brain injury is termed as",
    options: ["Ischaemic Stroke", "Completed stroke", "Progressive stroke", "Transient Ischaemic Attack"],
    correct: "Transient Ischaemic Attack",
    explanation: "A TIA resolves within 24 hours and does not leave persistent deficits by definition.",
    explainCorrect: "Transient Ischaemic Attack is correct.",
  },
  {
    id: 1271,
    type: "single",
    category: "Cardiovascular Disorders",
    question: "Q13. Which antihypertensive has been shown to have mild uricosuric effects in patients with GOUT?",
    options: ["Lisinopril", "Amlodipine", "Losartan", "Propranolol"],
    correct: "Losartan",
    explanation: "Losartan has a mild uricosuric effect and is often favored in patients with gout.",
    explainCorrect: "Losartan is the correct answer.",
  },
  {
    id: 1272,
    type: "single",
    category: "Infectious Diseases",
    question: "Q14. Which of the following organisms is an obligate intracellular bacteria, making it resistant to cell wall-active antibiotics?",
    options: ["Escherichia coli", "Staphylococcus aureus", "Streptococcus pneumoniae", "Chlamydophila pneumoniae"],
    correct: "Chlamydophila pneumoniae",
    explanation: "Chlamydial organisms are obligate intracellular pathogens.",
    explainCorrect: "Chlamydophila pneumoniae is correct.",
  },
  {
    id: 1273,
    type: "single",
    category: "Immunizations",
    question: "Q15. Achieving a high level of herd immunity is an important public health strategy because it:",
    options: ["reduces immunization costs in communities.", "enhances individual immunologic responses.", "protects people who cannot be immunized.", "requires fewer booster doses."],
    correct: "protects people who cannot be immunized.",
    explanation: "Herd immunity indirectly protects vulnerable people who cannot receive vaccines.",
    explainCorrect: "Protects people who cannot be immunized is correct.",
  },
  {
    id: 1274,
    type: "single",
    category: "Pharmaceutical Technology",
    question: "Q16. Diazepam Injection U.S.P Diazepam 5 mg/ml Ethanol 10% Propylene glycol 40% Benzyl alcohol 1.5% Water for Injection qs 100% In the formulation given above, propylene glycol functions as a(n):",
    options: ["emulsifier", "antioxidant", "co-solvent", "buffer"],
    correct: "co-solvent",
    explanation: "Propylene glycol is commonly used as a co-solvent in injectable formulations.",
    explainCorrect: "Co-solvent is the correct function.",
  },
  {
    id: 1275,
    type: "single",
    category: "Pharmaceutical Technology",
    question: "Q17. Reasons for using coatings on tablets include all of the following, EXCEPT to:",
    options: ["mask the taste of the drug", "mask the odor of the drug", "improve the appearance of the tablet", "increase the drug's release rate"],
    correct: "increase the drug's release rate",
    explanation: "Coatings usually mask taste and odor and improve appearance; they are not used to increase release rate in standard coating purposes.",
    explainCorrect: "Increase the drug's release rate is the exception.",
  },
  {
    id: 1276,
    type: "single",
    category: "Pharmaceutical Technology",
    question: "Q18. Which of the following terms indicates a loss of moisture?",
    options: ["Deliquescence", "Efflorescence", "Hygroscopicity", "Polymorphism"],
    correct: "Efflorescence",
    explanation: "Efflorescence is the loss of water of crystallisation from a substance.",
    explainCorrect: "Efflorescence is the correct answer.",
  },
  {
    id: 1277,
    type: "single",
    category: "Pharmaceutical Technology",
    question: "Q19. Which of the following statements is FALSE regarding tablet formulation?",
    options: ["Diluents are fillers to add bulk to the tablet", "Lubricants help the patient to swallow the tablet more easily", "Binding agents may be added dry or in solution", "Disintegrants draw water into the tablet causing it to burst"],
    correct: "Lubricants help the patient to swallow the tablet more easily",
    explanation: "Lubricants mainly reduce friction during compression and ejection; they do not primarily make swallowing easier.",
    explainCorrect: "The false statement is the one about lubricants helping swallowing.",
  },
  {
    id: 1278,
    type: "single",
    category: "Pharmacy Practice",
    question: "Q20. Atropine poisoning can be recognized by all of the following signs or symptoms, EXCEPT:",
    options: ["dry skin", "flushed appearance", "delirium and restlessness", "Diarrhea"],
    correct: "Diarrhea",
    explanation: "Atropine poisoning causes anticholinergic features such as dry skin, flushing, and delirium; diarrhea is not typical.",
    explainCorrect: "Diarrhea is the exception.",
  },
  {
    id: 1279,
    type: "single",
    category: "Pharmaceutical Technology",
    question: "Q21. In some parenteral formulations, sodium metabisulphite is included as:",
    options: ["an antioxidant", "a chelator", "a solubilizer", "a cosolvent"],
    correct: "an antioxidant",
    explanation: "Sodium metabisulphite is commonly used as an antioxidant preservative in formulations.",
    explainCorrect: "An antioxidant is correct.",
  },
  {
    id: 1280,
    type: "single",
    category: "Endocrinology",
    question: "Q22. Following successful resolution of an acute episode of gout, a patient given allopurinol should be advised to:",
    options: ["limit fluid intake", "take medication on an empty stomach", "use precautions to avoid photosensitivity", "report any skin rash or itching to the physician"],
    correct: "report any skin rash or itching to the physician",
    explanation: "Allopurinol can cause serious hypersensitivity reactions, so rash reporting is essential.",
    explainCorrect: "Report any skin rash or itching to the physician is the correct advice.",
  },
  {
    id: 1281,
    type: "single",
    category: "Gastrointestinal Disorders",
    question: "Q23. Lactose intolerance is classified as a(n):",
    options: ["allergy", "enzyme deficiency", "mineral deficiency", "transporter abnormality"],
    correct: "enzyme deficiency",
    explanation: "Lactose intolerance results from lactase deficiency.",
    explainCorrect: "Enzyme deficiency is correct.",
  },
  {
    id: 1282,
    type: "single",
    category: "Infectious Diseases",
    question: "Q24. WHO recommends that for Countries with HIV prevalence <5%, a one test algorithm is used to improve the true positivity rate hence the HIV testing updated to reflect a 3 test algorithm.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[3],
    explanation: "Low-prevalence settings generally require more confirmatory testing, so the one-test claim is false while the three-test approach is the correct principle.",
    explainCorrect: "The first statement is false and the second statement is true.",
  },
  {
    id: 1283,
    type: "single",
    category: "Infectious Diseases",
    question: "Q25. The early infant diagnosis of HIV policy in Ghana has been updated to include a mandatory retest at 9 months after testing negative within the first six weeks of life because all HIV exposed babies who test positive at 6 weeks are put on ART.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[1],
    explanation: "The retest schedule and the fact that positive infants start ART are both true, but the second statement is not the explanation for the retest requirement.",
    explainCorrect: "Both statements are true but the second is not a correct explanation of the first.",
  },
  {
    id: 1284,
    type: "single",
    category: "Infectious Diseases",
    question: "Q26. During HIV testing and counselling process, there is the need for a written consent from the one receiving the counseling because client must understand the purpose and benefits of testing.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[3],
    explanation: "Consent and understanding are required, but written consent is not always the required form in routine HIV testing settings.",
    explainCorrect: "The first statement is false and the second statement is true.",
  },
  {
    id: 1285,
    type: "single",
    category: "Infectious Diseases",
    question: "Q27. The management of people living with HIV is best achieved using a multidisciplinary team approach because the psychosocial support provider is always the team lead.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[2],
    explanation: "Multidisciplinary care is correct, but the psychosocial support provider is not always the team lead.",
    explainCorrect: "The first statement is true and the second statement is false.",
  },
  {
    id: 1286,
    type: "single",
    category: "Infectious Diseases",
    question: "Q28. There is always the need to confirm HIV infection at the point of ART initiation because the current national guidelines recommend this.",
    options: assertionReasonOptions,
    correct: assertionReasonOptions[0],
    explanation: "Confirming HIV status before ART initiation is guideline-driven, so both statements are true and the reason supports the assertion.",
    explainCorrect: "Both statements are true and the second is a correct explanation of the first.",
  },
  {
    id: 1287,
    type: "single",
    category: "Oncology",
    question: "Q29. Which of the following is not a characteristic of a benign tumour?",
    options: ["High mitotic index", "Well differentiated", "Well-defined capsule", "Does not metastasize"],
    correct: "High mitotic index",
    explanation: "Benign tumours are usually well differentiated, encapsulated, and non-metastatic.",
    explainCorrect: "High mitotic index is the exception.",
  },
  {
    id: 1288,
    type: "single",
    category: "Oncology",
    question: "Q30. Trastuzumab is approved.....",
    options: ["For the indication of ER-positive breast cancer", "In neoadjuvant settings with any chemotherapy including anthracycline", "For patients overexpressing HER2 who have reduced left ventricular ejection fraction", "Not in combination with pertuzumab and other chemotherapy"],
    correct: "In neoadjuvant settings with any chemotherapy including anthracycline",
    explanation: "Trastuzumab is used in HER2-positive breast cancer and may form part of neoadjuvant treatment regimens; the other options are not correct here.",
    explainCorrect: "The neoadjuvant use option is the intended answer in this item.",
  },
  {
    id: 1289,
    type: "single",
    category: "Oncology",
    question: "Q31. All the following are premedication treatments with the administration of paclitaxel except",
    options: ["IV Paracetamol", "IV Dexamethasone", "IV Ranitidine", "IV Promethazine"],
    correct: "IV Paracetamol",
    explanation: "Paclitaxel premedication commonly includes corticosteroids and antihistamines; paracetamol is not a standard premedication component.",
    explainCorrect: "IV Paracetamol is the exception.",
  },
  {
    id: 1290,
    type: "single",
    category: "Pharmaceutical Technology",
    question: "Q32. Which of the following is not a constituent of Magic Solution?",
    options: ["Analgesic", "Antihistamine", "Antacid", "Anaesthetic agent"],
    correct: "Analgesic",
    explanation: "Magic solution formulations usually include an antacid, antihistamine, and local anaesthetic component.",
    explainCorrect: "Analgesic is the correct exception.",
  },
  {
    id: 1291,
    type: "single",
    category: "Oncology",
    question: "Q33. Which of the following are good prognostic factors in breast cancer?",
    options: ["Estrogen receptor positivity", "Grade III tumor", "HER 2-receptor over-expression", "Lymph node involvement"],
    correct: "Estrogen receptor positivity",
    explanation: "ER-positive breast cancer generally has a better prognosis and more treatment options.",
    explainCorrect: "Estrogen receptor positivity is the best prognostic factor listed.",
  },
  {
    id: 1292,
    type: "single",
    category: "Oncology",
    question: "Q34. In prostate cancer, side effects of hormone treatment rarely include one of the following?",
    options: ["Hot flushes", "Loss of libido and potency", "Osteoporosis", "Myelosuppression"],
    correct: "Myelosuppression",
    explanation: "Androgen deprivation commonly causes hot flushes, sexual dysfunction, and bone loss, but not myelosuppression as a usual effect.",
    explainCorrect: "Myelosuppression is the rare side effect here.",
  },
  {
    id: 1293,
    type: "single",
    category: "Oncology",
    question: "Q35. Which of the following statements about Granulocyte-colony stimulating factors (G-CSF) is true?",
    options: ["GCSF is used to prevent neutropenia during chemotherapy", "GCSF is not used in secondary prophylaxis", "GCSF can be administered at the same time with chemotherapy", "GCSF improves response to treatment"],
    correct: "GCSF is used to prevent neutropenia during chemotherapy",
    explanation: "G-CSF is used to reduce the risk of chemotherapy-induced neutropenia.",
    explainCorrect: "The prophylaxis statement is correct.",
  },
  {
    id: 1294,
    type: "single",
    category: "Oncology",
    question: "Q36. A daily dose of 90 mg morphine will require a breakthrough dose of:",
    options: ["10 mg Morphine", "20 mg Morphine", "15 mg Morphine", "30 mg Morphine"],
    correct: "10 mg Morphine",
    explanation: "Breakthrough doses are often about 10% of the total daily opioid dose, so 90 mg/day maps to about 10 mg.",
    explainCorrect: "10 mg Morphine is the best answer.",
  },
  {
    id: 1295,
    type: "single",
    category: "Infectious Diseases",
    question: "Q37. Select from A to D, which one of the above is indicated for the treatment of vancomycin-resistant enterococci.",
    options: ["A. Ceftaroline", "B. Piperacillin + Tazobactam", "C. Linezolid", "D. Flucloxacillin"],
    correct: "C. Linezolid",
    explanation: "Linezolid is active against vancomycin-resistant enterococci.",
    explainCorrect: "Option C is correct.",
  },
  {
    id: 1296,
    type: "single",
    category: "Infectious Diseases",
    question: "Q38. Select from A to D, which one of the above is particularly active against Pseudomonas aeruginosa.",
    options: ["A. Ceftaroline", "B. Piperacillin + Tazobactam", "C. Linezolid", "D. Flucloxacillin"],
    correct: "B. Piperacillin + Tazobactam",
    explanation: "Piperacillin/tazobactam has anti-pseudomonal activity.",
    explainCorrect: "Option B is correct.",
  },
  {
    id: 1297,
    type: "single",
    category: "Infectious Diseases",
    question: "Q39. Select from A to D, which one of the above is particularly active against methicillin-resistant Staphylococcus aureus and other Gram-positive bacteria.",
    options: ["A. Ceftaroline", "B. Piperacillin + Tazobactam", "C. Linezolid", "D. Flucloxacillin"],
    correct: "A. Ceftaroline",
    explanation: "Ceftaroline is a cephalosporin with activity against MRSA.",
    explainCorrect: "Option A is correct.",
  },
  {
    id: 1298,
    type: "single",
    category: "Infectious Diseases",
    question: "Q40. Select from A to D, which one of the above is particularly active against methicillin-sensitive Staphylococcus aureus.",
    options: ["A. Ceftaroline", "B. Piperacillin + Tazobactam", "C. Linezolid", "D. Flucloxacillin"],
    correct: "D. Flucloxacillin",
    explanation: "Flucloxacillin is a classic anti-staphylococcal penicillin for MSSA.",
    explainCorrect: "Option D is correct.",
  },
  {
    id: 1299,
    type: "combo",
    category: "Rheumatology & Pain",
    question: "Q41. Morphine is:",
    statements: [
      "An opioid analgesic",
      "Used in acute and chronic pain",
      "Capable of causing euphoria and mental detachment",
    ],
    correct: "A",
    explanation: "Morphine is an opioid analgesic used in acute and chronic pain and can cause euphoria and mental detachment.",
    explainCorrect: "Option A is correct because all three statements are true.",
  },
  {
    id: 1301,
    type: "single",
    category: "Renal Disorders",
    question: "Q43. A 47 year old woman with End Stage Renal Disease (ESRD) on hemodialysis presents with a traumatic fracture of the humerus. An orthopedic consultation recommends an open reduction and internal fixation to be performed the following day. Which of the following medications would you recommend for use in this patient?",
    options: ["Diclofenac", "Ibuprofen", "Naproxen", "Fentanyl"],
    correct: "Fentanyl",
    explanation: "Fentanyl is generally preferred over NSAIDs in severe renal impairment because it is safer for pain control in this context.",
    explainCorrect: "Fentanyl is the correct choice.",
  },
  {
    id: 1302,
    type: "single",
    category: "Renal Disorders",
    caseId: "mr-ab-ckd-anemia-hyperkalemia",
    caseBlock: "Mr. AB is being assessed for chronic kidney disease with anemia, urinary findings, hyperkalemia risk, and medication-related concerns. Use this case for the related questions.",
    question: "Q44. All these parameters are suggestive of Chronic Kidney Disease in Mr. AB EXCEPT",
    options: ["Abdominal scan showing reduction of kidney size", "Duration of the kidney disease i.e. 6 months", "Low hemoglobin", "Raised Jugular Venous Pressure (JVP)"],
    correct: "Raised Jugular Venous Pressure (JVP)",
    explanation: "Reduced kidney size, chronic duration, and anaemia support CKD; raised JVP is not a defining CKD criterion in this stem.",
    explainCorrect: "Raised JVP is the exception.",
  },
  {
    id: 1303,
    type: "single",
    category: "Hematology",
    caseId: "mr-ab-ckd-anemia-hyperkalemia",
    caseBlock: "Mr. AB is being assessed for chronic kidney disease with anemia, urinary findings, hyperkalemia risk, and medication-related concerns. Use this case for the related questions.",
    question: "Q45. The Spoon shaped nails, Angular stomatitis and Brittle hair in the above patient are suggestive of",
    options: ["Magnesium toxicity", "Folic acid deficiency", "Iron deficiency", "hyperkalemia"],
    correct: "Iron deficiency",
    explanation: "Koilonychia, angular stomatitis, and brittle hair are classic iron deficiency features.",
    explainCorrect: "Iron deficiency is correct.",
  },
  {
    id: 1304,
    type: "single",
    category: "Renal Disorders",
    caseId: "mr-ab-ckd-anemia-hyperkalemia",
    caseBlock: "Mr. AB is being assessed for chronic kidney disease with anemia, urinary findings, hyperkalemia risk, and medication-related concerns. Use this case for the related questions.",
    question: "Q46. Drug selection recommendations for renally impaired patient will include all of the following EXCEPT",
    options: ["Avoid medications excreted via the kidneys", "Consider dose reduction", "Decrease frequency of regimen", "Increase frequency of regimen"],
    correct: "Increase frequency of regimen",
    explanation: "Renal impairment usually requires dose reduction or interval extension, not increased frequency.",
    explainCorrect: "Increase frequency of regimen is the exception.",
  },
  {
    id: 1305,
    type: "single",
    category: "Renal Disorders",
    caseId: "mr-ab-ckd-anemia-hyperkalemia",
    caseBlock: "Mr. AB is being assessed for chronic kidney disease with anemia, urinary findings, hyperkalemia risk, and medication-related concerns. Use this case for the related questions.",
    question: "Q47. The Nitrite and Leucocyte esterase found in Mr. AB's urine dipstick are indicative of",
    options: ["Haemolysis", "Urinary Tract Infection", "Anaemia", "Acidosis"],
    correct: "Urinary Tract Infection",
    explanation: "Nitrites and leukocyte esterase on dipstick strongly suggest UTI.",
    explainCorrect: "Urinary Tract Infection is correct.",
  },
  {
    id: 1306,
    type: "single",
    category: "Renal Disorders",
    caseId: "mr-ab-ckd-anemia-hyperkalemia",
    caseBlock: "Mr. AB is being assessed for chronic kidney disease with anemia, urinary findings, hyperkalemia risk, and medication-related concerns. Use this case for the related questions.",
    question: "Q48. The low MCV in the above investigation is indicative of",
    options: ["UTI", "Folic Acid deficiency", "Iron deficiency", "Iron overload"],
    correct: "Iron deficiency",
    explanation: "A low MCV indicates microcytosis, most commonly due to iron deficiency in this stem.",
    explainCorrect: "Iron deficiency is correct.",
  },
  {
    id: 1307,
    type: "single",
    category: "Renal Disorders",
    caseId: "mr-ab-ckd-anemia-hyperkalemia",
    caseBlock: "Mr. AB is being assessed for chronic kidney disease with anemia, urinary findings, hyperkalemia risk, and medication-related concerns. Use this case for the related questions.",
    question: "Q49. All these may cause elevation of Potassium levels in the above patient EXCEPT",
    options: ["Metabolic Acidosis", "IV Clexane", "Lisinopril", "Metabolic Alkalosis"],
    correct: "Metabolic Alkalosis",
    explanation: "Metabolic alkalosis tends to lower serum potassium rather than increase it.",
    explainCorrect: "Metabolic Alkalosis is the exception.",
  },
  {
    id: 1308,
    type: "single",
    category: "Renal Disorders",
    caseId: "mr-ab-ckd-anemia-hyperkalemia",
    caseBlock: "Mr. AB is being assessed for chronic kidney disease with anemia, urinary findings, hyperkalemia risk, and medication-related concerns. Use this case for the related questions.",
    question: "Q50. All these medications should be discontinued from the above regimen EXCEPT",
    options: ["Nitrofurantoin", "Methyldopa", "Pioglitazone", "Lisinopril"],
    correct: "Methyldopa",
    explanation: "Methyldopa can still be used in renal impairment, while the other listed agents are less suitable in this stem.",
    explainCorrect: "Methyldopa is the exception.",
  },
  {
    id: 1309,
    type: "single",
    category: "Renal Disorders",
    caseId: "mr-ab-ckd-anemia-hyperkalemia",
    caseBlock: "Mr. AB is being assessed for chronic kidney disease with anemia, urinary findings, hyperkalemia risk, and medication-related concerns. Use this case for the related questions.",
    question: "Q51. Correction of Hyperkalemia in the above could be done using all these medications EXCEPT",
    options: ["Soluble Insulin", "Salbutamol Nebulization", "Kayexalate", "IV Clexane"],
    correct: "IV Clexane",
    explanation: "Clexane is not a hyperkalaemia treatment.",
    explainCorrect: "IV Clexane is the exception.",
  },
  {
    id: 1310,
    type: "single",
    category: "Hematology",
    caseId: "mr-ab-ckd-anemia-hyperkalemia",
    caseBlock: "Mr. AB is being assessed for chronic kidney disease with anemia, urinary findings, hyperkalemia risk, and medication-related concerns. Use this case for the related questions.",
    question: "Q52. High Rectic Count in the above case may be indicative of",
    options: ["Haemolysis", "Bone defects", "Iron deficiency", "Folic acid deficiency"],
    correct: "Haemolysis",
    explanation: "A high reticulocyte count suggests increased red cell production, commonly from haemolysis or blood loss.",
    explainCorrect: "Haemolysis is the correct answer.",
  },
  {
    id: 1311,
    type: "single",
    category: "Endocrinology",
    caseId: "mr-ab-ckd-anemia-hyperkalemia",
    caseBlock: "Mr. AB is being assessed for chronic kidney disease with anemia, urinary findings, hyperkalemia risk, and medication-related concerns. Use this case for the related questions.",
    question: "Q53. Regarding the use of Pioglitazone in the above treatment, it may",
    options: ["Reduce the risk of bladder cancer", "Cause dilutional Anaemia and worsen the existent anaemia", "Cause Dysuria", "Cause Hematuria"],
    correct: "Cause dilutional Anaemia and worsen the existent anaemia",
    explanation: "Pioglitazone can cause fluid retention and dilutional anaemia, which may worsen existing anaemia.",
    explainCorrect: "Cause dilutional Anaemia and worsen the existent anaemia is correct.",
  },
];
